// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package secretsdb

import (
	"context"
)

const addJobSecret = `-- name: AddJobSecret :exec
INSERT INTO job_secrets (job_id, secret_id, env_name) VALUES ($1, $2, $3)
`

type AddJobSecretParams struct {
	JobID    string
	SecretID string
	EnvName  string
}

func (q *Queries) AddJobSecret(ctx context.Context, arg AddJobSecretParams) error {
	_, err := q.db.ExecContext(ctx, addJobSecret, arg.JobID, arg.SecretID, arg.EnvName)
	return err
}

const clearJobSecrets = `-- name: ClearJobSecrets :exec
DELETE FROM job_secrets WHERE job_id = $1
`

func (q *Queries) ClearJobSecrets(ctx context.Context, jobID string) error {
	_, err := q.db.ExecContext(ctx, clearJobSecrets, jobID)
	return err
}

const createSecret = `-- name: CreateSecret :exec
INSERT INTO secrets (id, workspace_id, name, value_enc, key_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $6)
`

type CreateSecretParams struct {
	ID          string
	WorkspaceID string
	Name        string
	ValueEnc    []byte
	KeyID       string
	Now         int64
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) error {
	_, err := q.db.ExecContext(ctx, createSecret,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.ValueEnc,
		arg.KeyID,
		arg.Now,
	)
	return err
}

const deleteSecret = `-- name: DeleteSecret :execrows
DELETE FROM secrets WHERE workspace_id = $1 AND id = $2
`

type DeleteSecretParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSecret, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSecretByName = `-- name: GetSecretByName :one
SELECT id, workspace_id, name, value_enc, key_id, created_at, updated_at FROM secrets WHERE workspace_id = $1 AND name = $2
`

type GetSecretByNameParams struct {
	WorkspaceID string
	Name        string
}

func (q *Queries) GetSecretByName(ctx context.Context, arg GetSecretByNameParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, getSecretByName, arg.WorkspaceID, arg.Name)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ValueEnc,
		&i.KeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobSecrets = `-- name: ListJobSecrets :many
SELECT js.env_name, s.id, s.name, s.value_enc FROM job_secrets js JOIN secrets s ON s.id = js.secret_id
WHERE s.workspace_id = $1 AND js.job_id = $2 ORDER BY js.env_name
`

type ListJobSecretsParams struct {
	WorkspaceID string
	JobID       string
}

type ListJobSecretsRow struct {
	EnvName  string
	ID       string
	Name     string
	ValueEnc []byte
}

func (q *Queries) ListJobSecrets(ctx context.Context, arg ListJobSecretsParams) ([]ListJobSecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobSecrets, arg.WorkspaceID, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobSecretsRow{}
	for rows.Next() {
		var i ListJobSecretsRow
		if err := rows.Scan(
			&i.EnvName,
			&i.ID,
			&i.Name,
			&i.ValueEnc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretNames = `-- name: ListSecretNames :many
SELECT name FROM secrets WHERE workspace_id = $1 ORDER BY name
`

func (q *Queries) ListSecretNames(ctx context.Context, workspaceID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSecretNames, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const secretExists = `-- name: SecretExists :one
SELECT COUNT(*) FROM secrets WHERE workspace_id = $1 AND id = $2
`

type SecretExistsParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) SecretExists(ctx context.Context, arg SecretExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, secretExists, arg.WorkspaceID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateSecretValue = `-- name: UpdateSecretValue :execrows
UPDATE secrets SET value_enc = $1, key_id = $2, updated_at = $3
WHERE workspace_id = $4 AND id = $5
`

type UpdateSecretValueParams struct {
	ValueEnc    []byte
	KeyID       string
	UpdatedAt   int64
	WorkspaceID string
	ID          string
}

func (q *Queries) UpdateSecretValue(ctx context.Context, arg UpdateSecretValueParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSecretValue,
		arg.ValueEnc,
		arg.KeyID,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
