// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package notificationsdb

type ApiToken struct {
	ID          string
	WorkspaceID string
	Name        string
	TokenHash   string
	CreatedBy   *string
	CreatedAt   int64
	LastUsedAt  *int64
	ExpiresAt   *int64
}

type Blob struct {
	Key       string
	Data      []byte
	Size      int64
	UpdatedAt int64
}

type Image struct {
	ID             string
	JobID          string
	DockerfileHash string
	Dockerfile     string
	BaseDigest     *string
	Status         string
	Ref            *string
	Digest         *string
	SizeBytes      *int64
	Error          *string
	LogKey         *string
	CreatedAt      int64
	StartedAt      *int64
	FinishedAt     *int64
}

type Job struct {
	ID                  string
	WorkspaceID         string
	Name                string
	Instruction         string
	Spec                string
	ModelID             *string
	Image               *string
	Network             string
	AllowedDomains      string
	AllowPrivateNetwork bool
	RunAsRoot           bool
	Limits              string
	SelfImprove         bool
	Graduate            bool
	GraduatedVersion    *int64
	PlaybookVersion     int64
	Concurrency         string
	Cron                *string
	Timezone            *string
	NextRunAt           *int64
	WebhookTokenHash    *string
	RunCounter          int64
	CreatedBy           *string
	CreatedAt           int64
	UpdatedAt           int64
	ArchivedAt          *int64
}

type JobMcpServer struct {
	JobID        string
	McpServerID  string
	AllowedTools *string
}

type JobSecret struct {
	JobID    string
	SecretID string
	EnvName  string
}

type JobState struct {
	JobID     string
	Key       string
	Value     string
	UpdatedAt int64
}

type Kv struct {
	Key   string
	Value string
}

type McpServer struct {
	ID               string
	WorkspaceID      string
	Name             string
	Description      *string
	Transport        string
	Command          *string
	Args             string
	Env              string
	Url              *string
	Headers          string
	ToolsCache       *string
	ToolsCachedAt    *int64
	Enabled          bool
	OauthConfig      string
	OauthSupported   *bool
	OauthCredentials []byte
	OauthKeyID       *string
	OauthExpiresAt   *int64
	OauthRefreshable bool
	OauthLoggedInAt  *int64
	OauthPending     []byte
	CreatedAt        int64
	UpdatedAt        int64
}

type Model struct {
	ID              string
	WorkspaceID     string
	ProviderID      string
	Model           string
	Label           *string
	PriceIn         int64
	PriceOut        int64
	PriceCacheRead  int64
	PriceCacheWrite int64
	ContextWindow   int64
	Caps            string
	Enabled         bool
	Synced          bool
	FollowCatalog   bool
	UnlistedAt      *int64
	CreatedAt       int64
}

type ModelCatalog struct {
	Source    string
	Data      string
	FetchedAt int64
}

type Passkey struct {
	ID           string
	UserID       string
	CredentialID string
	Name         string
	Credential   string
	CreatedAt    int64
	LastUsedAt   *int64
}

type PasskeyCeremony struct {
	TokenHash string
	Kind      string
	Data      string
	ExpiresAt int64
}

type PlaybookStat struct {
	JobID     string
	Kind      string
	Name      string
	Hits      int64
	Calls     int64
	Failures  int64
	UpdatedAt int64
}

type PlaybookVersion struct {
	JobID          string
	Version        int64
	Content        string
	Ops            *string
	Summary        *string
	DockerfileHash *string
	Author         string
	AuthorUserID   *string
	SourceRunID    *string
	CreatedAt      int64
}

type Provider struct {
	ID          string
	WorkspaceID string
	Name        string
	Kind        string
	BaseUrl     *string
	ApiKeyEnc   []byte
	KeyID       *string
	SyncedAt    *int64
	SyncError   *string
	CreatedAt   int64
}

type Run struct {
	ID                    string
	WorkspaceID           string
	JobID                 string
	Number                int64
	Status                string
	Mode                  string
	FellBack              bool
	Trigger               string
	TriggeredBy           *string
	Input                 *string
	Instructions          *string
	PlaybookVersion       int64
	ModelID               *string
	ImageID               *string
	ImageRef              *string
	HostID                *string
	HeartbeatAt           *int64
	BrokerTokenHash       *string
	SandboxAdapter        *string
	SandboxID             *string
	SandboxIsolation      *string
	QueuedAt              int64
	StartedAt             *int64
	FinishedAt            *int64
	MsQueue               *int64
	MsProvision           *int64
	MsLlm                 int64
	MsTools               int64
	MsTotal               *int64
	Turns                 int64
	TokIn                 int64
	TokOut                int64
	TokCacheRead          int64
	TokCacheWrite         int64
	Cost                  int64
	Summary               *string
	Outputs               *string
	Error                 *string
	CancelRequested       bool
	Reflection            string
	ReflectionRequestedAt *int64
	ReflectionError       *string
	ReflectionSummary     *string
	ReflectionOps         *string
	ReflectionVersion     *int64
	ReflectionCost        int64
	ReflectionTokens      int64
	VerifyCost            int64
	VerifyTokens          int64
}

type RunEvent struct {
	RunID   string
	Seq     int64
	Ts      int64
	Type    string
	SpanID  *string
	Ms      *int64
	Payload string
}

type Secret struct {
	ID          string
	WorkspaceID string
	Name        string
	ValueEnc    []byte
	KeyID       string
	CreatedAt   int64
	UpdatedAt   int64
}

type Session struct {
	TokenHash string
	UserID    string
	CreatedAt int64
	ExpiresAt int64
}

type Setting struct {
	WorkspaceID string
	Key         string
	Value       string
}

type SignInLink struct {
	TokenHash string
	UserID    string
	CreatedAt int64
	ExpiresAt int64
}

type User struct {
	ID              string
	Issuer          string
	Subject         string
	Email           *string
	EmailVerified   bool
	Name            *string
	Picture         *string
	IsAdmin         bool
	DisabledAt      *int64
	LastWorkspaceID *string
	CreatedAt       int64
	LastLoginAt     *int64
}

type Workspace struct {
	ID        string
	Name      string
	CreatedAt int64
}

type WorkspaceInvite struct {
	ID          string
	WorkspaceID string
	Role        string
	Email       *string
	TokenHash   *string
	CreatedBy   *string
	CreatedAt   int64
	ExpiresAt   int64
}

type WorkspaceMember struct {
	WorkspaceID string
	UserID      string
	Role        string
	CreatedAt   int64
}
