// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package notificationsdb

import (
	"context"
)

const getRunDetails = `-- name: GetRunDetails :one
SELECT r.id, r.job_id, j.name AS job_name, r.number, r.status, r.mode, r.trigger, r.fell_back, r.error
FROM runs r JOIN jobs j ON j.id = r.job_id
WHERE r.workspace_id = $1 AND r.id = $2
`

type GetRunDetailsParams struct {
	WorkspaceID string
	ID          string
}

type GetRunDetailsRow struct {
	ID       string
	JobID    string
	JobName  string
	Number   int64
	Status   string
	Mode     string
	Trigger  string
	FellBack bool
	Error    *string
}

func (q *Queries) GetRunDetails(ctx context.Context, arg GetRunDetailsParams) (GetRunDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getRunDetails, arg.WorkspaceID, arg.ID)
	var i GetRunDetailsRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.JobName,
		&i.Number,
		&i.Status,
		&i.Mode,
		&i.Trigger,
		&i.FellBack,
		&i.Error,
	)
	return i, err
}
