/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/auth/callback': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['login-callback'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/login': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['login'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/logout': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['logout'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/catalog/models': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get-model-catalog'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/events': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['stream-workspace-events'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/jobs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['list-jobs'];
		put?: never;
		post: operations['create-job'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/jobs/compile': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['compile-job'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/jobs/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get-job'];
		put?: never;
		post?: never;
		delete: operations['delete-job'];
		options?: never;
		head?: never;
		patch: operations['update-job'];
		trace?: never;
	};
	'/api/jobs/{id}/images': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['list-job-images'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/jobs/{id}/images/rebuild': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['rebuild-job-image'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/jobs/{id}/images/{imageId}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get-image'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/jobs/{id}/mcp-servers': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get-job-mcp-servers'];
		put: operations['set-job-mcp-servers'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/jobs/{id}/playbook': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get-playbook'];
		put: operations['update-playbook'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/jobs/{id}/playbook/rollback': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['rollback-playbook'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/jobs/{id}/playbook/versions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['list-playbook-versions'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/jobs/{id}/playbook/versions/{version}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get-playbook-version'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/jobs/{id}/runs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['run-job'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/jobs/{id}/secrets': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get-job-secrets'];
		put: operations['set-job-secrets'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/jobs/{id}/state': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['list-job-state'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/jobs/{id}/state/{key}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get-job-state'];
		put: operations['put-job-state'];
		post?: never;
		delete: operations['delete-job-state'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/jobs/{id}/stats': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get-job-stats'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/jobs/{id}/webhook-token': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['rotate-webhook-token'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/mcp-servers': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['list-mcp-servers'];
		put?: never;
		post: operations['create-mcp-server'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/mcp-servers/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get-mcp-server'];
		put: operations['update-mcp-server'];
		post?: never;
		delete: operations['delete-mcp-server'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/mcp-servers/{id}/oauth': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: operations['logout-mcp-server'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/mcp-servers/{id}/oauth/callback': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['mcp-server-oauth-callback'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/mcp-servers/{id}/oauth/login': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['login-mcp-server'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/mcp-servers/{id}/test': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['test-mcp-server'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/models': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['list-models'];
		put?: never;
		post: operations['create-model'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/models/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: operations['delete-model'];
		options?: never;
		head?: never;
		patch: operations['update-model'];
		trace?: never;
	};
	'/api/providers': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['list-providers'];
		put?: never;
		post: operations['create-provider'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/providers/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: operations['delete-provider'];
		options?: never;
		head?: never;
		patch: operations['update-provider'];
		trace?: never;
	};
	'/api/providers/{id}/models/enabled': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: operations['set-provider-models-enabled'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/providers/{id}/sync': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['sync-provider-models'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/providers/{id}/test': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['test-provider'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/runs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['list-runs'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/runs/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get-run'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/runs/{id}/artifact': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get-run-artifact'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/runs/{id}/artifacts': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['list-run-artifacts'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/runs/{id}/cancel': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['cancel-run'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/runs/{id}/events': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['list-run-events'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/runs/{id}/learn': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['learn-from-run'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/runs/{id}/retry': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['retry-run'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/runs/{id}/stream': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['stream-run'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/secrets': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['list-secrets'];
		put?: never;
		post: operations['create-secret'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/secrets/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: operations['update-secret'];
		post?: never;
		delete: operations['delete-secret'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/settings': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get-settings'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch: operations['update-settings'];
		trace?: never;
	};
	'/api/settings/notifications/test': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['test-notification'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/stats/overview': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get-stats-overview'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/system/info': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get-system-info'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/tokens': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['list-api-tokens'];
		put?: never;
		post: operations['create-api-token'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/tokens/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: operations['delete-api-token'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/users/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get-current-user'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/hooks/{jobId}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['trigger-webhook'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		ApiTokenDto: {
			/** Format: int64 */
			createdAt: number;
			/** Format: int64 */
			expiresAt: number | null;
			id: string;
			/** Format: int64 */
			lastUsedAt: number | null;
			name: string;
		};
		AppliedOp: {
			content: string | null;
			flags?: string[] | null;
			id: string | null;
			kind: string | null;
			name: string | null;
			/** @enum {string} */
			op:
				| 'add_learning'
				| 'update_learning'
				| 'retire_learning'
				| 'upsert_script'
				| 'delete_script'
				| 'set_setup'
				| 'set_dockerfile'
				| 'propose_main'
				| 'update_main'
				| 'set_verify';
			rationale: string;
			reason?: string;
			/** @enum {string} */
			status: 'applied' | 'held' | 'rejected';
			target?: string;
			test?: components['schemas']['OpTest'];
			text: string | null;
			when: string | null;
		};
		ArtifactDto: {
			name: string;
			/** Format: int64 */
			size: number;
		};
		AuthDto: {
			/** @description Where the authorization server sends the browser back to, which an OAuth client configured by hand must allow */
			callbackUrl?: string;
			/**
			 * Format: int64
			 * @description When the current access token expires
			 */
			expiresAt: number | null;
			/**
			 * Format: int64
			 * @description When the OAuth login was made, also set once it expired
			 */
			loggedInAt: number | null;
			/** @description The login has a refresh token, so it outlives its access token */
			refreshable: boolean;
			/**
			 * @description unsupported: no login needed or possible, unknown: OAuth detection hasn't succeeded yet, bearer_token: an Authorization header is configured, not_logged_in: the server advertises OAuth but has no usable login, oauth: logged in
			 * @enum {string}
			 */
			status: 'unsupported' | 'unknown' | 'bearer_token' | 'not_logged_in' | 'oauth';
		};
		Body: {
			code: string;
			details?: {
				[key: string]: string;
			};
			fields?: components['schemas']['FieldError'][] | null;
			message: string;
			requestId?: string;
		};
		Caps: {
			/** Format: int64 */
			context: number;
			jsonSchema: boolean;
			parallelTools: boolean;
			promptCache: boolean;
			reasoning: boolean;
			tools: boolean;
			vision: boolean;
		};
		CatalogEntryDto: {
			caps: components['schemas']['Caps'];
			label: string;
			model: string;
			price: components['schemas']['Price'];
		};
		CheaperJob: {
			/** Format: double */
			dropPct: number;
			/** Format: int64 */
			firstCost: number;
			jobId: string;
			jobName: string;
			/** Format: int64 */
			recentCost: number;
			/** Format: int64 */
			runs: number;
		};
		CompileInputBody: {
			instruction: string;
		};
		Content: {
			dockerfile: string | null;
			learnings: components['schemas']['Learning'][] | null;
			main: string | null;
			setup: string | null;
			toolkit: components['schemas']['Script'][] | null;
			verify?: unknown;
		};
		Cookie: {
			Domain: string;
			/** Format: date-time */
			Expires: string;
			HttpOnly: boolean;
			/** Format: int64 */
			MaxAge: number;
			Name: string;
			Partitioned: boolean;
			Path: string;
			Quoted: boolean;
			Raw: string;
			RawExpires: string;
			/** Format: int64 */
			SameSite: number;
			Secure: boolean;
			Unparsed: string[] | null;
			Value: string;
		};
		CreateInputBody: {
			/**
			 * Format: int64
			 * @description Unix milliseconds; omit for a token that never expires
			 */
			expiresAt?: number;
			name: string;
		};
		CreateInputBody1: {
			name: string;
			value: string;
		};
		CreateModelInputBody: {
			caps: components['schemas']['Caps'];
			label?: string;
			model: string;
			price: components['schemas']['Price'];
			providerId: string;
		};
		CreateOutputBody: {
			apiToken: components['schemas']['ApiTokenDto'];
			/** @description Shown once, store it now */
			token: string;
		};
		CreateProviderInputBody: {
			apiKey?: string;
			baseUrl?: string;
			/** @enum {string} */
			kind: 'anthropic' | 'openai' | 'fake';
			name: string;
		};
		CreateProviderOutputBody: {
			id: string;
			sync: components['schemas']['SyncResult'];
		};
		DayBucket: {
			/** Format: int64 */
			cancelled: number;
			/** Format: int64 */
			cost: number;
			/** Format: int64 */
			day: number;
			/** Format: int64 */
			failed: number;
			/** Format: int64 */
			other: number;
			/** Format: int64 */
			skipped: number;
			/** Format: int64 */
			succeeded: number;
			/** Format: int64 */
			timedOut: number;
		};
		DeltaDto: {
			callId?: string;
			text?: string;
			type: string;
		};
		EndDto: {
			status: string;
		};
		EventDto: {
			/** Format: int64 */
			ms: number | null;
			parentSpanId: string | null;
			payload: unknown;
			/** Format: int64 */
			seq: number;
			spanId: string | null;
			/** Format: int64 */
			ts: number;
			type: string;
		};
		FieldError: {
			code: string;
			field: string;
			message: string;
		};
		GetOutputBody: {
			baseDigest: string | null;
			/** Format: int64 */
			createdAt: number;
			digest: string | null;
			dockerfile: string;
			dockerfileHash: string;
			error: string | null;
			/** Format: int64 */
			finishedAt: number | null;
			id: string;
			log: string;
			ref: string | null;
			/** Format: int64 */
			sizeBytes: number | null;
			/** Format: int64 */
			startedAt: number | null;
			status: string;
		};
		IOField: {
			description?: string;
			name: string;
			type: string;
		};
		IdOutputBody: {
			id: string;
		};
		ImageDto: {
			baseDigest: string | null;
			/** Format: int64 */
			createdAt: number;
			digest: string | null;
			dockerfileHash: string;
			error: string | null;
			/** Format: int64 */
			finishedAt: number | null;
			id: string;
			ref: string | null;
			/** Format: int64 */
			sizeBytes: number | null;
			/** Format: int64 */
			startedAt: number | null;
			status: string;
		};
		ImageIDOutputBody: {
			id: string;
		};
		InfoOutputBody: {
			allowPrivateNetworkTargets: boolean;
			database: string;
			sandbox: unknown;
			version: string;
		};
		JobCost: {
			/** Format: int64 */
			cost: number;
			/** Format: int64 */
			day: number;
			jobId: string;
			jobName: string;
		};
		JobDto: {
			allowPrivateNetwork: boolean;
			allowedDomains: string[] | null;
			concurrency: string;
			/** Format: int64 */
			createdAt: number;
			cron: string | null;
			demoted: boolean;
			enabled: boolean;
			/**
			 * Format: int64
			 * @description The playbook version the job last graduated to Scripted mode at
			 */
			graduatedVersion: number | null;
			hasWebhookToken: boolean;
			id: string;
			image: string | null;
			instruction: string;
			lastRun: components['schemas']['LastRun'];
			limits: components['schemas']['LimitOverrides'];
			modePin: string | null;
			modelId: string | null;
			name: string;
			/** @enum {string} */
			network: 'none' | 'internet' | 'allowlist';
			/** @enum {string} */
			nextMode?: 'explore' | 'assisted' | 'scripted';
			/** Format: int64 */
			nextRunAt: number | null;
			/** Format: int64 */
			playbookVersion: number;
			runAsRoot: boolean;
			selfImprove: boolean;
			spec: components['schemas']['Spec'];
			timezone: string | null;
			/** Format: int64 */
			updatedAt: number;
		};
		JobFields: {
			allowPrivateNetwork?: boolean;
			allowedDomains?: string[] | null;
			/** @enum {string} */
			concurrency?: 'skip' | 'queue' | 'parallel';
			cron?: string;
			enabled?: boolean;
			image?: string;
			instruction: string;
			limits?: components['schemas']['LimitOverrides'];
			/** @enum {string} */
			modePin?: 'explore' | 'assisted' | 'scripted';
			modelId?: string;
			name: string;
			/** @enum {string} */
			network?: 'none' | 'internet' | 'allowlist';
			runAsRoot?: boolean;
			selfImprove?: boolean;
			spec?: components['schemas']['Spec'];
			timezone?: string;
		};
		JobListDto: {
			/** Format: int64 */
			createdAt: number;
			cron: string | null;
			enabled: boolean;
			id: string;
			lastMode: string | null;
			lastRun: components['schemas']['LastRun'];
			modePin: string | null;
			name: string;
			/** Format: int64 */
			nextRunAt: number | null;
			/** Format: int64 */
			runCount: number;
			scheduleHuman: string | null;
			timezone: string | null;
			/** Format: int64 */
			updatedAt: number;
		};
		JobPatch: {
			allowPrivateNetwork?: boolean;
			allowedDomains?: string[];
			/** @enum {string} */
			concurrency?: 'skip' | 'queue' | 'parallel';
			cron?: string;
			enabled?: boolean;
			image?: string;
			instruction?: string;
			limits?: components['schemas']['LimitOverrides'];
			/** @enum {string} */
			modePin?: 'explore' | 'assisted' | 'scripted' | '';
			modelId?: string;
			name?: string;
			/** @enum {string} */
			network?: 'none' | 'internet' | 'allowlist';
			runAsRoot?: boolean;
			selfImprove?: boolean;
			spec?: components['schemas']['Spec'];
			timezone?: string;
		};
		JobRunPoint: {
			/** Format: int64 */
			cost: number;
			mode: string;
			/** Format: int64 */
			msTotal: number | null;
			/** Format: int64 */
			number: number;
			/** Format: int64 */
			playbookVersion: number;
			/** Format: int64 */
			queuedAt: number;
			runId: string;
			status: string;
			/** Format: int64 */
			turns: number;
		};
		JobSecret: {
			envName: string;
			secretId: string;
			readonly secretName?: string;
		};
		JobServer: {
			/** @description null exposes all tools */
			allowedTools: string[] | null;
			serverId: string;
			readonly serverName?: string;
		};
		JobStatsOutputBody: {
			/** Format: int64 */
			avgCost: number;
			/** Format: int64 */
			p50Ms: number;
			runs: components['schemas']['JobRunPoint'][] | null;
			/** Format: double */
			successRate: number;
			versions: components['schemas']['VersionMarker'][] | null;
		};
		LastRun: {
			id: string;
			/** Format: int64 */
			number: number;
			/** Format: int64 */
			queuedAt: number;
			status: string;
		};
		LearnOutputBody: {
			reflection: string;
		};
		Learning: {
			/** Format: int64 */
			hits: number;
			id: string;
			kind: string;
			sources?: string[] | null;
			/** @enum {string} */
			status: 'active' | 'retired';
			text: string;
			when?: string;
		};
		LimitOverrides: {
			/** Format: double */
			cpus?: number;
			/** Format: double */
			maxCostUsd?: number;
			/** Format: int64 */
			maxTurns?: number;
			/** Format: int64 */
			memoryMb?: number;
			/** Format: int64 */
			pidsLimit?: number;
			/** Format: int64 */
			timeoutSeconds?: number;
		};
		Limits: {
			/** Format: double */
			cpus: number;
			/** Format: double */
			maxCostUsd: number;
			/** Format: int64 */
			maxTurns: number;
			/** Format: int64 */
			memoryMb: number;
			/** Format: int64 */
			pidsLimit: number;
			/** Format: int64 */
			timeoutSeconds: number;
		};
		LoginOutputBody: {
			/** @description Where to send the browser to log in */
			authorizationUrl: string;
		};
		MCPNeed: {
			server: string;
			why: string;
		};
		ModelDto: {
			caps: components['schemas']['Caps'];
			/** Format: int64 */
			contextWindow: number;
			enabled: boolean;
			followCatalog: boolean;
			id: string;
			label: string | null;
			model: string;
			/** @description Micro-USD per 1M tokens */
			price: components['schemas']['Price'];
			providerId: string;
			providerKind: string;
			providerName: string;
			synced: boolean;
			/** Format: int64 */
			unlistedAt: number | null;
		};
		OauthConfig: {
			/** @description A client registered with the authorization server beforehand, for servers without dynamic client registration */
			clientId?: string;
			/** @description The client's secret, may reference a secret as {{secret:NAME}} */
			clientSecret?: string;
			/** @description Scopes to request instead of the ones the server advertises */
			scopes?: string[] | null;
		};
		OpTest: {
			detail: string;
			output?: string;
			/** @enum {string} */
			status: 'passed' | 'failed' | 'skipped';
		};
		OverviewOutputBody: {
			costByJob: components['schemas']['JobCost'][] | null;
			current: components['schemas']['Totals'];
			gettingCheaper: components['schemas']['CheaperJob'][] | null;
			perDay: components['schemas']['DayBucket'][] | null;
			previous: components['schemas']['Totals'];
			range: string;
			recentFailures: components['schemas']['RunRef'][] | null;
			running: components['schemas']['RunRef'][] | null;
		};
		PaginatedApiTokenDto: {
			items: components['schemas']['ApiTokenDto'][];
			/** Format: int64 */
			page: number;
			/** Format: int64 */
			pageSize: number;
			/** Format: int64 */
			total: number;
		};
		PaginatedImageDto: {
			items: components['schemas']['ImageDto'][];
			/** Format: int64 */
			page: number;
			/** Format: int64 */
			pageSize: number;
			/** Format: int64 */
			total: number;
		};
		PaginatedJobListDto: {
			items: components['schemas']['JobListDto'][];
			/** Format: int64 */
			page: number;
			/** Format: int64 */
			pageSize: number;
			/** Format: int64 */
			total: number;
		};
		PaginatedModelDto: {
			items: components['schemas']['ModelDto'][];
			/** Format: int64 */
			page: number;
			/** Format: int64 */
			pageSize: number;
			/** Format: int64 */
			total: number;
		};
		PaginatedProviderDto: {
			items: components['schemas']['ProviderDto'][];
			/** Format: int64 */
			page: number;
			/** Format: int64 */
			pageSize: number;
			/** Format: int64 */
			total: number;
		};
		PaginatedRunDto: {
			items: components['schemas']['RunDto'][];
			/** Format: int64 */
			page: number;
			/** Format: int64 */
			pageSize: number;
			/** Format: int64 */
			total: number;
		};
		PaginatedSecretDto: {
			items: components['schemas']['SecretDto'][];
			/** Format: int64 */
			page: number;
			/** Format: int64 */
			pageSize: number;
			/** Format: int64 */
			total: number;
		};
		PaginatedServerDto: {
			items: components['schemas']['ServerDto'][];
			/** Format: int64 */
			page: number;
			/** Format: int64 */
			pageSize: number;
			/** Format: int64 */
			total: number;
		};
		PaginatedStateEntryDto: {
			items: components['schemas']['StateEntryDto'][];
			/** Format: int64 */
			page: number;
			/** Format: int64 */
			pageSize: number;
			/** Format: int64 */
			total: number;
		};
		PaginatedVersionListDto: {
			items: components['schemas']['VersionListDto'][];
			/** Format: int64 */
			page: number;
			/** Format: int64 */
			pageSize: number;
			/** Format: int64 */
			total: number;
		};
		Price: {
			/** Format: int64 */
			cacheRead: number;
			/** Format: int64 */
			cacheWrite: number;
			/** Format: int64 */
			in: number;
			/** Format: int64 */
			out: number;
		};
		ProviderDto: {
			baseUrl: string | null;
			/** Format: int64 */
			createdAt: number;
			/** Format: int64 */
			enabledModelCount: number;
			hasApiKey: boolean;
			id: string;
			kind: string;
			/** Format: int64 */
			modelCount: number;
			/**
			 * @description catalog: the models.dev catalog of the kind, server: the server's model list, manual: models are added by hand
			 * @enum {string}
			 */
			modelSource: 'catalog' | 'server' | 'manual';
			name: string;
			/** @description Why the last sync could not read the model list */
			syncError: string | null;
			/** Format: int64 */
			syncedAt: number | null;
		};
		ProviderIDOutputBody: {
			id: string;
		};
		PutStateInputBody: {
			value: string;
		};
		RollbackInputBody: {
			/** Format: int64 */
			version: number;
		};
		RunDetailDto: {
			cancelRequested: boolean;
			/**
			 * Format: int64
			 * @description Micro-USD
			 */
			cost: number;
			error: string | null;
			fellBack: boolean;
			/** Format: int64 */
			finishedAt: number | null;
			id: string;
			imageRef: string | null;
			input: unknown;
			instructions: string | null;
			jobId: string;
			jobName: string;
			mode: string;
			modelName: string | null;
			/** Format: int64 */
			msLlm: number;
			/** Format: int64 */
			msProvision: number | null;
			/** Format: int64 */
			msQueue: number | null;
			/** Format: int64 */
			msTools: number;
			/** Format: int64 */
			msTotal: number | null;
			/** Format: int64 */
			number: number;
			outputs: unknown;
			/** Format: int64 */
			playbookVersion: number;
			/** Format: int64 */
			queuedAt: number;
			/** @enum {string} */
			reflection: 'skipped' | 'pending' | 'done' | 'failed';
			/**
			 * Format: int64
			 * @description Micro-USD
			 */
			reflectionCost: number;
			reflectionError: string | null;
			reflectionOps: components['schemas']['AppliedOp'][] | null;
			reflectionSummary: string | null;
			/**
			 * Format: int64
			 * @description The playbook version reflection on this run created
			 */
			reflectionVersion: number | null;
			sandboxAdapter: string | null;
			sandboxIsolation: string | null;
			/** Format: int64 */
			startedAt: number | null;
			status: string;
			summary: string | null;
			/** Format: int64 */
			tokCacheRead: number;
			/** Format: int64 */
			tokCacheWrite: number;
			/** Format: int64 */
			tokIn: number;
			/** Format: int64 */
			tokOut: number;
			trigger: string;
			triggeredBy: string | null;
			/** @description Name or email of the user who started the run */
			triggeredByName: string | null;
			/** Format: int64 */
			turns: number;
			/**
			 * Format: int64
			 * @description What the utility model's verification of a scripted run cost, in micro-USD
			 */
			verifyCost: number;
		};
		RunDto: {
			/**
			 * Format: int64
			 * @description Micro-USD
			 */
			cost: number;
			error: string | null;
			/** Format: int64 */
			finishedAt: number | null;
			id: string;
			jobId: string;
			jobName: string;
			mode: string;
			modelName: string | null;
			/** Format: int64 */
			msLlm: number;
			/** Format: int64 */
			msProvision: number | null;
			/** Format: int64 */
			msQueue: number | null;
			/** Format: int64 */
			msTools: number;
			/** Format: int64 */
			msTotal: number | null;
			/** Format: int64 */
			number: number;
			/** Format: int64 */
			queuedAt: number;
			sandboxIsolation: string | null;
			/** Format: int64 */
			startedAt: number | null;
			status: string;
			summary: string | null;
			/** Format: int64 */
			tokCacheRead: number;
			/** Format: int64 */
			tokCacheWrite: number;
			/** Format: int64 */
			tokIn: number;
			/** Format: int64 */
			tokOut: number;
			trigger: string;
			/** Format: int64 */
			turns: number;
		};
		RunNowInputBody: {
			/** @description Run input, available as /ump/input.json */
			input?: unknown;
			/** @description Additional instructions for this run only */
			instructions?: string;
		};
		RunRef: {
			error: string | null;
			id: string;
			jobId: string;
			jobName: string;
			mode: string;
			/** Format: int64 */
			number: number;
			/** Format: int64 */
			queuedAt: number;
			/** Format: int64 */
			startedAt: number | null;
			status: string;
		};
		Schedule: {
			cron: string;
			human: string;
			timezone: string;
		};
		Script: {
			args?: unknown;
			content: string;
			description: string;
			lang: string;
			name: string;
			sideEffects: boolean;
			sources?: string[] | null;
			stats: components['schemas']['ScriptStats'];
		};
		ScriptStats: {
			/** Format: int64 */
			calls: number;
			/** Format: int64 */
			failures: number;
		};
		SecretDto: {
			/** Format: int64 */
			createdAt: number;
			id: string;
			name: string;
			/** Format: int64 */
			updatedAt: number;
		};
		ServerBody: {
			args?: string[] | null;
			command?: string;
			description?: string;
			enabled?: boolean;
			env?: {
				[key: string]: string;
			};
			headers?: {
				[key: string]: string;
			};
			name: string;
			/** @description OAuth client settings of HTTP servers, only needed when the server's authorization server can't register clients itself */
			oauth?: components['schemas']['OauthConfig'];
			/** @enum {string} */
			transport: 'stdio' | 'http';
			url?: string;
		};
		ServerDto: {
			args: string[] | null;
			auth: components['schemas']['AuthDto'];
			command: string | null;
			/** Format: int64 */
			createdAt: number;
			description: string | null;
			enabled: boolean;
			/** @description Values may reference secrets as {{secret:NAME}} */
			env: {
				[key: string]: string;
			};
			/** @description Values may reference secrets as {{secret:NAME}} */
			headers: {
				[key: string]: string;
			};
			id: string;
			name: string;
			oauth: components['schemas']['OauthConfig'];
			tools: components['schemas']['ToolInfo'][] | null;
			/** Format: int64 */
			toolsCachedAt: number | null;
			transport: string;
			/** Format: int64 */
			updatedAt: number;
			url: string | null;
		};
		SetEnabledInputBody: {
			enabled: boolean;
		};
		SetEnabledOutputBody: {
			/** Format: int64 */
			changed: number;
		};
		Spec: {
			dockerfile: string | null;
			goal: string;
			inputs: components['schemas']['IOField'][] | null;
			mcp: components['schemas']['MCPNeed'][] | null;
			/** @enum {string} */
			network: 'none' | 'internet';
			outputs: components['schemas']['IOField'][] | null;
			schedule?: components['schemas']['Schedule'];
			sideEffects: string[] | null;
			successCriteria: string[] | null;
			title: string;
			warnings: string[] | null;
		};
		StateEntryDto: {
			key: string;
			/** Format: int64 */
			updatedAt: number;
			value: string;
		};
		StatusDto: {
			status: string;
		};
		SyncResult: {
			/** Format: int64 */
			added: number;
			error?: string;
			/** Format: int64 */
			unlisted: number;
			/** Format: int64 */
			updated: number;
		};
		TestOutputBody: {
			/** @description The server's authentication status after the test */
			auth: components['schemas']['AuthDto'];
			error?: string;
			/** Format: int64 */
			latencyMs: number;
			ok: boolean;
			tools: components['schemas']['ToolInfo'][] | null;
		};
		TestOutputBody1: {
			delivered: boolean;
		};
		TestProviderInputBody: {
			/** @description Model to test with */
			modelId: string;
		};
		TestProviderOutputBody: {
			error?: string;
			/** Format: int64 */
			latencyMs: number;
			ok: boolean;
			reply?: string;
		};
		ToolInfo: {
			description: string;
			destructive: boolean;
			inputSchema: unknown;
			name: string;
			readOnly: boolean;
		};
		Totals: {
			/** Format: int64 */
			failed: number;
			/**
			 * Format: int64
			 * @description Micro-USD
			 */
			learningCost: number;
			/** Format: int64 */
			p50Ms: number;
			/** Format: int64 */
			p95Ms: number;
			/**
			 * Format: int64
			 * @description Micro-USD
			 */
			runCost: number;
			/** Format: int64 */
			runs: number;
			/** Format: int64 */
			succeeded: number;
			/** Format: double */
			successRate: number;
		};
		TriggerResult: {
			runId: string;
			status: string;
		};
		UpdateInputBody: {
			agentModelId?: string;
			/** Format: double */
			dailySpendLimitUsd?: number;
			/** @description An empty value resets to the server default */
			defaultImage?: string;
			defaultLimits?: components['schemas']['Limits'];
			notifyOn?: ('run.failed' | 'run.fell_back' | 'job.demoted')[] | null;
			/** @description An empty value sends deliveries unsigned */
			notifySecret?: string;
			/** @description An empty value turns notifications off */
			notifyWebhookUrl?: string;
			reflectionModelId?: string;
			/** Format: int64 */
			retentionDays?: number;
			utilityModelId?: string;
		};
		UpdateInputBody1: {
			/**
			 * Format: int64
			 * @description The version the edit started from; a newer current version makes the save fail with 409
			 */
			baseVersion?: number;
			content: components['schemas']['Content'];
			summary?: string;
		};
		UpdateInputBody2: {
			value: string;
		};
		UpdateModelInputBody: {
			caps?: components['schemas']['Caps'];
			enabled?: boolean;
			followCatalog?: boolean;
			label?: string;
			price?: components['schemas']['Price'];
		};
		UpdateProviderInputBody: {
			apiKey?: string;
			baseUrl?: string;
			name?: string;
		};
		UserDto: {
			email: string | null;
			id: string;
			name: string | null;
			viaToken: boolean;
			workspaceId: string;
		};
		VersionDto: {
			author: string;
			content: components['schemas']['Content'];
			/** Format: int64 */
			createdAt: number;
			ops?: components['schemas']['AppliedOp'][] | null;
			previous?: components['schemas']['Content'];
			sourceRunId: string | null;
			summary: string | null;
			/** Format: int64 */
			version: number;
		};
		VersionListDto: {
			author: string;
			/** Format: int64 */
			createdAt: number;
			sourceRunId: string | null;
			summary: string | null;
			/** Format: int64 */
			version: number;
		};
		VersionMarker: {
			author: string;
			/** Format: int64 */
			createdAt: number;
			/** Format: int64 */
			version: number;
		};
		WebhookTokenOutputBody: {
			/** @description Shown once */
			token: string;
			url: string;
		};
		WorkspaceEventDto: {
			jobId?: string;
			/** @enum {string} */
			kind: 'run' | 'reflection';
			runId?: string;
			status?: string;
		};
		WorkspaceSettings: {
			agentModelId: string | null;
			/**
			 * Format: double
			 * @description 0 means no limit
			 */
			dailySpendLimitUsd: number;
			defaultImage: string;
			defaultLimits: components['schemas']['Limits'];
			notifyOn: ('run.failed' | 'run.fell_back' | 'job.demoted')[] | null;
			/** @description Name of a workspace secret whose value signs every delivery */
			notifySecret: string | null;
			notifyWebhookUrl: string | null;
			reflectionModelId: string | null;
			/** Format: int64 */
			retentionDays: number;
			utilityModelId: string | null;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	'login-callback': {
		parameters: {
			query?: {
				code?: string;
				state?: string;
				error?: string;
			};
			header?: never;
			path?: never;
			cookie?: {
				umpteenth_login?: components['schemas']['Cookie'];
			};
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					Location?: string;
					'Set-Cookie'?: string;
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	login: {
		parameters: {
			query?: {
				/** @description Relative path to return to after login */
				redirect?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					Location?: string;
					'Set-Cookie'?: string;
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	logout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					'Set-Cookie'?: string;
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'get-model-catalog': {
		parameters: {
			query?: {
				kind?: 'anthropic' | 'openai';
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['CatalogEntryDto'][] | null;
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'stream-workspace-events': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/event-stream': {
						data: components['schemas']['WorkspaceEventDto'];
						/**
						 * @description The event name.
						 * @constant
						 */
						event: 'run';
						/** @description The event ID. */
						id?: number;
						/** @description The retry time in milliseconds. */
						retry?: number;
					}[];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'list-jobs': {
		parameters: {
			query?: {
				/** @description 1-based page number */
				page?: number;
				/** @description Items per page */
				pageSize?: number;
				/** @description Comma-separated sort keys, prefix with - for descending */
				sort?: string;
				/** @description Free-text search */
				search?: string;
				/** @description Comma-separated enabled states, true and/or false */
				enabled?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedJobListDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'create-job': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['JobFields'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JobDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'compile-job': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CompileInputBody'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Spec'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'get-job': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JobDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'delete-job': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'update-job': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['JobPatch'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JobDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'list-job-images': {
		parameters: {
			query?: {
				/** @description 1-based page number */
				page?: number;
				/** @description Items per page */
				pageSize?: number;
				/** @description Comma-separated sort keys, prefix with - for descending */
				sort?: string;
				/** @description Free-text search */
				search?: string;
				status?: string;
			};
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedImageDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'rebuild-job-image': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ImageIDOutputBody'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'get-image': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				imageId: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GetOutputBody'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'get-job-mcp-servers': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JobServer'][] | null;
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'set-job-mcp-servers': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['JobServer'][] | null;
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JobServer'][] | null;
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'get-playbook': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['VersionDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'update-playbook': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateInputBody1'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['VersionDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'rollback-playbook': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RollbackInputBody'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['VersionDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'list-playbook-versions': {
		parameters: {
			query?: {
				/** @description 1-based page number */
				page?: number;
				/** @description Items per page */
				pageSize?: number;
				/** @description Comma-separated sort keys, prefix with - for descending */
				sort?: string;
				/** @description Free-text search */
				search?: string;
			};
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedVersionListDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'get-playbook-version': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				version: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['VersionDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'run-job': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RunNowInputBody'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['TriggerResult'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'get-job-secrets': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JobSecret'][] | null;
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'set-job-secrets': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['JobSecret'][] | null;
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JobSecret'][] | null;
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'list-job-state': {
		parameters: {
			query?: {
				/** @description 1-based page number */
				page?: number;
				/** @description Items per page */
				pageSize?: number;
				/** @description Comma-separated sort keys, prefix with - for descending */
				sort?: string;
				/** @description Free-text search */
				search?: string;
			};
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedStateEntryDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'get-job-state': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				key: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StateEntryDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'put-job-state': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				key: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['PutStateInputBody'];
			};
		};
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'delete-job-state': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
				key: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'get-job-stats': {
		parameters: {
			query?: {
				range?: '7d' | '30d' | '90d';
			};
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JobStatsOutputBody'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'rotate-webhook-token': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WebhookTokenOutputBody'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'list-mcp-servers': {
		parameters: {
			query?: {
				/** @description 1-based page number */
				page?: number;
				/** @description Items per page */
				pageSize?: number;
				/** @description Comma-separated sort keys, prefix with - for descending */
				sort?: string;
				/** @description Free-text search */
				search?: string;
				transport?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedServerDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'create-mcp-server': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ServerBody'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServerDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'get-mcp-server': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServerDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'update-mcp-server': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ServerBody'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServerDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'delete-mcp-server': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'logout-mcp-server': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServerDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'mcp-server-oauth-callback': {
		parameters: {
			query?: {
				code?: string;
				state?: string;
				iss?: string;
				error?: string;
				error_description?: string;
			};
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					Location?: string;
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'login-mcp-server': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LoginOutputBody'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'test-mcp-server': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['TestOutputBody'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'list-models': {
		parameters: {
			query?: {
				/** @description 1-based page number */
				page?: number;
				/** @description Items per page */
				pageSize?: number;
				/** @description Comma-separated sort keys, prefix with - for descending */
				sort?: string;
				/** @description Free-text search */
				search?: string;
				/** @description Comma-separated provider IDs */
				provider?: string;
				/** @description Comma-separated statuses: enabled (can be picked), disabled, unlisted */
				status?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedModelDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'create-model': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateModelInputBody'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ProviderIDOutputBody'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'delete-model': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'update-model': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateModelInputBody'];
			};
		};
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'list-providers': {
		parameters: {
			query?: {
				/** @description 1-based page number */
				page?: number;
				/** @description Items per page */
				pageSize?: number;
				/** @description Comma-separated sort keys, prefix with - for descending */
				sort?: string;
				/** @description Free-text search */
				search?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedProviderDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'create-provider': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateProviderInputBody'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['CreateProviderOutputBody'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'delete-provider': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'update-provider': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateProviderInputBody'];
			};
		};
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'set-provider-models-enabled': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SetEnabledInputBody'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SetEnabledOutputBody'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'sync-provider-models': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SyncResult'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'test-provider': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['TestProviderInputBody'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['TestProviderOutputBody'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'list-runs': {
		parameters: {
			query?: {
				/** @description 1-based page number */
				page?: number;
				/** @description Items per page */
				pageSize?: number;
				/** @description Comma-separated sort keys, prefix with - for descending */
				sort?: string;
				/** @description Free-text search */
				search?: string;
				/** @description Comma-separated statuses */
				status?: string;
				/** @description Comma-separated job IDs */
				job?: string;
				/** @description Comma-separated modes */
				mode?: string;
				/** @description Comma-separated triggers */
				trigger?: string;
				/** @description Queued at or after, unix ms */
				from?: number;
				/** @description Queued before, unix ms */
				to?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedRunDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'get-run': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['RunDetailDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'get-run-artifact': {
		parameters: {
			query: {
				path: string;
			};
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'list-run-artifacts': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ArtifactDto'][] | null;
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'cancel-run': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'list-run-events': {
		parameters: {
			query?: {
				/** @description Return events with a sequence number greater than this */
				after?: number;
				limit?: number;
			};
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['EventDto'][] | null;
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'learn-from-run': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LearnOutputBody'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'retry-run': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['TriggerResult'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'stream-run': {
		parameters: {
			query?: {
				/** @description Resume after this event sequence, for clients that cannot send Last-Event-ID */
				after?: number;
			};
			header?: {
				'Last-Event-ID'?: string;
			};
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/event-stream': (
						| {
								data: components['schemas']['DeltaDto'];
								/**
								 * @description The event name.
								 * @constant
								 */
								event: 'delta';
								/** @description The event ID. */
								id?: number;
								/** @description The retry time in milliseconds. */
								retry?: number;
						  }
						| {
								data: components['schemas']['EndDto'];
								/**
								 * @description The event name.
								 * @constant
								 */
								event: 'end';
								/** @description The event ID. */
								id?: number;
								/** @description The retry time in milliseconds. */
								retry?: number;
						  }
						| {
								data: components['schemas']['EventDto'];
								/**
								 * @description The event name.
								 * @constant
								 */
								event: 'event';
								/** @description The event ID. */
								id?: number;
								/** @description The retry time in milliseconds. */
								retry?: number;
						  }
						| {
								data: components['schemas']['StatusDto'];
								/**
								 * @description The event name.
								 * @constant
								 */
								event: 'status';
								/** @description The event ID. */
								id?: number;
								/** @description The retry time in milliseconds. */
								retry?: number;
						  }
					)[];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'list-secrets': {
		parameters: {
			query?: {
				/** @description 1-based page number */
				page?: number;
				/** @description Items per page */
				pageSize?: number;
				/** @description Comma-separated sort keys, prefix with - for descending */
				sort?: string;
				/** @description Free-text search */
				search?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedSecretDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'create-secret': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateInputBody1'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['IdOutputBody'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'update-secret': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateInputBody2'];
			};
		};
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'delete-secret': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'get-settings': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkspaceSettings'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'update-settings': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateInputBody'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkspaceSettings'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'test-notification': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['TestOutputBody1'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'get-stats-overview': {
		parameters: {
			query?: {
				range?: '24h' | '7d' | '30d' | '90d';
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['OverviewOutputBody'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'get-system-info': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['InfoOutputBody'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'list-api-tokens': {
		parameters: {
			query?: {
				/** @description 1-based page number */
				page?: number;
				/** @description Items per page */
				pageSize?: number;
				/** @description Comma-separated sort keys, prefix with - for descending */
				sort?: string;
				/** @description Free-text search */
				search?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedApiTokenDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'create-api-token': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateInputBody'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['CreateOutputBody'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'delete-api-token': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'get-current-user': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UserDto'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
	'trigger-webhook': {
		parameters: {
			query?: never;
			header?: {
				Authorization?: string;
			};
			path: {
				jobId: string;
			};
			cookie?: never;
		};
		requestBody?: {
			content: {
				'application/octet-stream': string;
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['TriggerResult'];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Body'];
				};
			};
		};
	};
}
