// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package workspacesdb

import (
	"context"
)

const ensureWorkspace = `-- name: EnsureWorkspace :exec
INSERT INTO workspaces (id, name, created_at) VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type EnsureWorkspaceParams struct {
	ID        string
	Name      string
	CreatedAt int64
}

func (q *Queries) EnsureWorkspace(ctx context.Context, arg EnsureWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, ensureWorkspace, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, created_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
