// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package workspacesdb

import (
	"context"
)

const addMember = `-- name: AddMember :execrows
INSERT INTO workspace_members (workspace_id, user_id, role, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddMemberParams struct {
	WorkspaceID string
	UserID      string
	Role        string
	CreatedAt   int64
}

// A user who is a member already keeps their role, and the unique owner index makes a second owner a no-op instead of an error that would abort the transaction
func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addMember,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimOwnerless = `-- name: ClaimOwnerless :execrows
INSERT INTO workspace_members (workspace_id, user_id, role, created_at)
SELECT w.id, $1, 'owner', $2 FROM workspaces w
WHERE w.id = $3 AND NOT EXISTS (SELECT 1 FROM workspace_members o WHERE o.workspace_id = w.id AND o.role = 'owner')
ON CONFLICT DO NOTHING
`

type ClaimOwnerlessParams struct {
	UserID      string
	CreatedAt   int64
	WorkspaceID string
}

// The first member of a workspace without an owner becomes its owner, which is how a fresh instance gets one
func (q *Queries) ClaimOwnerless(ctx context.Context, arg ClaimOwnerlessParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimOwnerless, arg.UserID, arg.CreatedAt, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countUserMemberships = `-- name: CountUserMemberships :one
SELECT COUNT(*) FROM workspace_members WHERE user_id = $1
`

// unscoped: counts the user's memberships across workspaces
func (q *Queries) CountUserMemberships(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserMemberships, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspace = `-- name: CountWorkspace :one
SELECT COUNT(*) FROM workspaces WHERE id = $1
`

func (q *Queries) CountWorkspace(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkspace, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLinkInvite = `-- name: CreateLinkInvite :exec
INSERT INTO workspace_invites (id, workspace_id, role, token_hash, created_by, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateLinkInviteParams struct {
	ID          string
	WorkspaceID string
	Role        string
	TokenHash   *string
	CreatedBy   *string
	CreatedAt   int64
	ExpiresAt   int64
}

func (q *Queries) CreateLinkInvite(ctx context.Context, arg CreateLinkInviteParams) error {
	_, err := q.db.ExecContext(ctx, createLinkInvite,
		arg.ID,
		arg.WorkspaceID,
		arg.Role,
		arg.TokenHash,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO workspaces (id, name, created_at) VALUES ($1, $2, $3)
`

type CreateWorkspaceParams struct {
	ID        string
	Name      string
	CreatedAt int64
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspace, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const deleteInvite = `-- name: DeleteInvite :execrows
DELETE FROM workspace_invites WHERE workspace_id = $1 AND id = $2
`

type DeleteInviteParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInvite, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteWorkspace = `-- name: DeleteWorkspace :execrows
DELETE FROM workspaces WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureWorkspace = `-- name: EnsureWorkspace :exec
INSERT INTO workspaces (id, name, created_at) VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type EnsureWorkspaceParams struct {
	ID        string
	Name      string
	CreatedAt int64
}

func (q *Queries) EnsureWorkspace(ctx context.Context, arg EnsureWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, ensureWorkspace, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const ensureWorkspaceIfNone = `-- name: EnsureWorkspaceIfNone :exec
INSERT INTO workspaces (id, name, created_at)
SELECT $1, $2, $3 WHERE NOT EXISTS (SELECT 1 FROM workspaces)
ON CONFLICT (id) DO NOTHING
`

type EnsureWorkspaceIfNoneParams struct {
	ID        string
	Name      string
	CreatedAt int64
}

// Only a fresh instance gets the default workspace, so one that was deleted doesn't come back
func (q *Queries) EnsureWorkspaceIfNone(ctx context.Context, arg EnsureWorkspaceIfNoneParams) error {
	_, err := q.db.ExecContext(ctx, ensureWorkspaceIfNone, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const findVerifiedUsersByEmail = `-- name: FindVerifiedUsersByEmail :many
SELECT id FROM users WHERE LOWER(email) = $1 AND email_verified = TRUE AND disabled_at IS NULL LIMIT 2
`

// unscoped: users are instance-wide, and only an address the sign-in provider vouched for may join someone to a workspace
func (q *Queries) FindVerifiedUsersByEmail(ctx context.Context, email *string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, findVerifiedUsersByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccess = `-- name: GetAccess :one
SELECT u.is_admin, u.disabled_at, m.role, (SELECT COUNT(*) FROM workspaces w WHERE w.id = $1) AS workspace_count
FROM users u
LEFT JOIN workspace_members m ON m.user_id = u.id AND m.workspace_id = $1
WHERE u.id = $2
`

type GetAccessParams struct {
	WorkspaceID string
	UserID      string
}

type GetAccessRow struct {
	IsAdmin        bool
	DisabledAt     *int64
	Role           *string
	WorkspaceCount int64
}

// One query answers every authenticated request: whether the user may still sign in, is an instance admin, and which role they have in the workspace
func (q *Queries) GetAccess(ctx context.Context, arg GetAccessParams) (GetAccessRow, error) {
	row := q.db.QueryRowContext(ctx, getAccess, arg.WorkspaceID, arg.UserID)
	var i GetAccessRow
	err := row.Scan(
		&i.IsAdmin,
		&i.DisabledAt,
		&i.Role,
		&i.WorkspaceCount,
	)
	return i, err
}

const getInvite = `-- name: GetInvite :one
SELECT id, workspace_id, role, email, created_at, expires_at FROM workspace_invites WHERE workspace_id = $1 AND id = $2
`

type GetInviteParams struct {
	WorkspaceID string
	ID          string
}

type GetInviteRow struct {
	ID          string
	WorkspaceID string
	Role        string
	Email       *string
	CreatedAt   int64
	ExpiresAt   int64
}

func (q *Queries) GetInvite(ctx context.Context, arg GetInviteParams) (GetInviteRow, error) {
	row := q.db.QueryRowContext(ctx, getInvite, arg.WorkspaceID, arg.ID)
	var i GetInviteRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Role,
		&i.Email,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT i.id, i.workspace_id, i.role, i.expires_at, w.name AS workspace_name, u.name AS created_by_name, u.email AS created_by_email
FROM workspace_invites i
JOIN workspaces w ON w.id = i.workspace_id
LEFT JOIN users u ON u.id = i.created_by
WHERE i.token_hash = $1
`

type GetInviteByTokenHashRow struct {
	ID             string
	WorkspaceID    string
	Role           string
	ExpiresAt      int64
	WorkspaceName  string
	CreatedByName  *string
	CreatedByEmail *string
}

// unscoped: the token hash is what identifies the invite and its workspace
func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash *string) (GetInviteByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getInviteByTokenHash, tokenHash)
	var i GetInviteByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Role,
		&i.ExpiresAt,
		&i.WorkspaceName,
		&i.CreatedByName,
		&i.CreatedByEmail,
	)
	return i, err
}

const getLoginUser = `-- name: GetLoginUser :one
SELECT name, email, last_workspace_id FROM users WHERE id = $1
`

type GetLoginUserRow struct {
	Name            *string
	Email           *string
	LastWorkspaceID *string
}

// unscoped: users are instance-wide
func (q *Queries) GetLoginUser(ctx context.Context, id string) (GetLoginUserRow, error) {
	row := q.db.QueryRowContext(ctx, getLoginUser, id)
	var i GetLoginUserRow
	err := row.Scan(&i.Name, &i.Email, &i.LastWorkspaceID)
	return i, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM workspace_members WHERE workspace_id = $1 AND user_id = $2
`

type GetMemberRoleParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getMemberRole, arg.WorkspaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getOwner = `-- name: GetOwner :one
SELECT user_id FROM workspace_members WHERE workspace_id = $1 AND role = 'owner'
`

func (q *Queries) GetOwner(ctx context.Context, workspaceID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getOwner, workspaceID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, created_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listEmailInvites = `-- name: ListEmailInvites :many
SELECT id, workspace_id, role FROM workspace_invites WHERE email = $1 AND expires_at > $2 ORDER BY created_at, id
`

type ListEmailInvitesParams struct {
	Email *string
	Now   int64
}

type ListEmailInvitesRow struct {
	ID          string
	WorkspaceID string
	Role        string
}

// unscoped: finds the invites to the user's verified address in every workspace
func (q *Queries) ListEmailInvites(ctx context.Context, arg ListEmailInvitesParams) ([]ListEmailInvitesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmailInvites, arg.Email, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmailInvitesRow{}
	for rows.Next() {
		var i ListEmailInvitesRow
		if err := rows.Scan(&i.ID, &i.WorkspaceID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvites = `-- name: ListInvites :many
SELECT i.id, i.role, i.email, i.created_at, i.expires_at, u.name AS created_by_name, u.email AS created_by_email
FROM workspace_invites i
LEFT JOIN users u ON u.id = i.created_by
WHERE i.workspace_id = $1
ORDER BY i.created_at DESC, i.id
`

type ListInvitesRow struct {
	ID             string
	Role           string
	Email          *string
	CreatedAt      int64
	ExpiresAt      int64
	CreatedByName  *string
	CreatedByEmail *string
}

func (q *Queries) ListInvites(ctx context.Context, workspaceID string) ([]ListInvitesRow, error) {
	rows, err := q.db.QueryContext(ctx, listInvites, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitesRow{}
	for rows.Next() {
		var i ListInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Email,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.CreatedByName,
			&i.CreatedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWorkspaces = `-- name: ListUserWorkspaces :many
SELECT w.id, w.name, m.role FROM workspace_members m
JOIN workspaces w ON w.id = m.workspace_id
WHERE m.user_id = $1
ORDER BY LOWER(w.name), w.id
`

type ListUserWorkspacesRow struct {
	ID   string
	Name string
	Role string
}

// unscoped: lists the user's workspaces across the instance
func (q *Queries) ListUserWorkspaces(ctx context.Context, userID string) ([]ListUserWorkspacesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserWorkspaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserWorkspacesRow{}
	for rows.Next() {
		var i ListUserWorkspacesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :exec
UPDATE users SET last_login_at = last_login_at WHERE id = $1
`

// unscoped: users are instance-wide
// Writing the row makes concurrent sign-ins of the same user wait for each other on Postgres, where SQLite serializes writes anyway
func (q *Queries) LockUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, lockUser, id)
	return err
}

const oldestMembership = `-- name: OldestMembership :one
SELECT workspace_id FROM workspace_members WHERE user_id = $1 ORDER BY created_at, workspace_id LIMIT 1
`

// unscoped: looks across the user's workspaces for the one to land in
func (q *Queries) OldestMembership(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRowContext(ctx, oldestMembership, userID)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const removeMember = `-- name: RemoveMember :execrows
DELETE FROM workspace_members WHERE workspace_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeMember, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renameWorkspace = `-- name: RenameWorkspace :execrows
UPDATE workspaces SET name = $1 WHERE id = $2
`

type RenameWorkspaceParams struct {
	Name string
	ID   string
}

func (q *Queries) RenameWorkspace(ctx context.Context, arg RenameWorkspaceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameWorkspace, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setLastWorkspace = `-- name: SetLastWorkspace :exec
UPDATE users SET last_workspace_id = $1 WHERE id = $2
`

type SetLastWorkspaceParams struct {
	WorkspaceID *string
	ID          string
}

// unscoped: users are instance-wide
func (q *Queries) SetLastWorkspace(ctx context.Context, arg SetLastWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, setLastWorkspace, arg.WorkspaceID, arg.ID)
	return err
}

const setMemberRole = `-- name: SetMemberRole :execrows
UPDATE workspace_members SET role = $1 WHERE workspace_id = $2 AND user_id = $3
`

type SetMemberRoleParams struct {
	Role        string
	WorkspaceID string
	UserID      string
}

func (q *Queries) SetMemberRole(ctx context.Context, arg SetMemberRoleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setMemberRole, arg.Role, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertEmailInvite = `-- name: UpsertEmailInvite :one
INSERT INTO workspace_invites (id, workspace_id, role, email, created_by, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (workspace_id, email) DO UPDATE SET role = excluded.role, created_by = excluded.created_by, created_at = excluded.created_at, expires_at = excluded.expires_at
RETURNING id
`

type UpsertEmailInviteParams struct {
	ID          string
	WorkspaceID string
	Role        string
	Email       *string
	CreatedBy   *string
	CreatedAt   int64
	ExpiresAt   int64
}

// Inviting an address again refreshes the invite instead of failing
func (q *Queries) UpsertEmailInvite(ctx context.Context, arg UpsertEmailInviteParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertEmailInvite,
		arg.ID,
		arg.WorkspaceID,
		arg.Role,
		arg.Email,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
