#!/usr/bin/env bash
# Generates the sqlc configs from every internal/<module>/queries.sql and runs sqlc
# The Postgres config produces the code; the SQLite config only compiles the same queries against the SQLite schema to catch non-portable SQL
set -euo pipefail
cd "$(dirname "$0")/.."

write_config() {
  local engine="$1" schema="$2" out_root="$3" file="$4"
  {
    echo "# Generated by scripts/sqlc.sh, do not edit"
    echo 'version: "2"'
    echo "sql:"
    for q in internal/*/queries.sql; do
      local module
      module="$(basename "$(dirname "$q")")"
      cat <<YAML
  - engine: ${engine}
    schema: ${schema}
    queries: ${q}
    gen:
      go:
        package: ${module}db
        out: ${out_root}/${module}/${module}db
        sql_package: database/sql
        emit_empty_slices: true
        overrides:
          - db_type: text
            nullable: true
            go_type: { type: string, pointer: true }
          - db_type: pg_catalog.int8
            nullable: true
            go_type: { type: int64, pointer: true }
          - db_type: pg_catalog.int4
            go_type: { type: int64 }
          - db_type: pg_catalog.bool
            nullable: true
            go_type: { type: bool, pointer: true }
YAML
    done
  } > "$file"
}

write_config postgresql resources/migrations/postgres internal sqlc.yaml
go tool sqlc generate -f sqlc.yaml

# Compile-only check against SQLite, output is discarded
check=".sqlc.sqlite.yaml"
trap 'rm -f "$check"' EXIT
write_config sqlite resources/migrations/sqlite /tmp/umpteenth-sqlc-check "$check"
go tool sqlc compile -f "$check"
