// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package settingsdb

import (
	"context"
)

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings WHERE workspace_id = $1 AND key = $2
`

type DeleteSettingParams struct {
	WorkspaceID string
	Key         string
}

func (q *Queries) DeleteSetting(ctx context.Context, arg DeleteSettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, arg.WorkspaceID, arg.Key)
	return err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value FROM settings WHERE workspace_id = $1
`

type ListSettingsRow struct {
	Key   string
	Value string
}

func (q *Queries) ListSettings(ctx context.Context, workspaceID string) ([]ListSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSettings, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSettingsRow{}
	for rows.Next() {
		var i ListSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (workspace_id, key, value) VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, key) DO UPDATE SET value = excluded.value
`

type UpsertSettingParams struct {
	WorkspaceID string
	Key         string
	Value       string
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.WorkspaceID, arg.Key, arg.Value)
	return err
}
