// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package apitokensdb

import (
	"context"
)

const createAPIToken = `-- name: CreateAPIToken :exec
INSERT INTO api_tokens (id, workspace_id, name, token_hash, created_by, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAPITokenParams struct {
	ID          string
	WorkspaceID string
	Name        string
	TokenHash   string
	CreatedBy   *string
	CreatedAt   int64
	ExpiresAt   *int64
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, createAPIToken,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteAPIToken = `-- name: DeleteAPIToken :execrows
DELETE FROM api_tokens WHERE workspace_id = $1 AND id = $2
`

type DeleteAPITokenParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAPIToken, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, workspace_id, name, token_hash, created_by, created_at, last_used_at, expires_at FROM api_tokens WHERE token_hash = $1
`

// unscoped: the token hash is what identifies the workspace
func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = $1 WHERE id = $2
`

type TouchAPITokenParams struct {
	LastUsedAt *int64
	ID         string
}

// unscoped: called right after the token was resolved by its hash
func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIToken, arg.LastUsedAt, arg.ID)
	return err
}
