// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package reflectiondb

import (
	"context"
)

const addReflectionSpend = `-- name: AddReflectionSpend :exec
UPDATE runs SET reflection_cost = reflection_cost + $1, reflection_tokens = reflection_tokens + $2
WHERE workspace_id = $3 AND id = $4
`

type AddReflectionSpendParams struct {
	Cost        int64
	Tokens      int64
	WorkspaceID string
	ID          string
}

// A reflection's cost and tokens count whether or not its result was recorded, since they were spent
func (q *Queries) AddReflectionSpend(ctx context.Context, arg AddReflectionSpendParams) error {
	_, err := q.db.ExecContext(ctx, addReflectionSpend,
		arg.Cost,
		arg.Tokens,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const claimReflection = `-- name: ClaimReflection :execrows
UPDATE runs SET reflection_requested_at = $1
WHERE workspace_id = $2 AND id = $3 AND reflection = 'pending'
  AND (CAST($4 AS BIGINT) IS NULL OR reflection_requested_at = CAST($4 AS BIGINT))
`

type ClaimReflectionParams struct {
	ClaimedAt   *int64
	WorkspaceID string
	ID          string
	RequestedAt *int64
}

// The task that starts a reflection moves its request time to now, so the reconciler counts from the start and not from the wait in the queue
// The new time identifies the claim, so a task that claims the run after it, e.g. a retry on another replica, takes over and only the latest claim records a result
func (q *Queries) ClaimReflection(ctx context.Context, arg ClaimReflectionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimReflection,
		arg.ClaimedAt,
		arg.WorkspaceID,
		arg.ID,
		arg.RequestedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failStalePending = `-- name: FailStalePending :execrows
UPDATE runs SET reflection = 'failed', reflection_error = 'Reflection did not finish, start it again from the run page'
WHERE reflection = 'pending' AND reflection_requested_at < $1
`

// unscoped: the reconciler ends reflections across workspaces whose task was lost, so they can be started again
func (q *Queries) FailStalePending(ctx context.Context, cutoff *int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, failStalePending, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishReflection = `-- name: FinishReflection :execrows
UPDATE runs SET reflection = $1, reflection_error = $2, reflection_summary = $3,
  reflection_ops = $4, reflection_version = $5
WHERE workspace_id = $6 AND id = $7 AND reflection = 'pending'
  AND (CAST($8 AS BIGINT) IS NULL OR reflection_requested_at = CAST($8 AS BIGINT))
`

type FinishReflectionParams struct {
	Reflection        string
	ReflectionError   *string
	ReflectionSummary *string
	ReflectionOps     *string
	ReflectionVersion *int64
	WorkspaceID       string
	ID                string
	RequestedAt       *int64
}

// Only the reflection that is still pending records its result, so one the reconciler gave up on can't overwrite a newer one or clear its pending state
func (q *Queries) FinishReflection(ctx context.Context, arg FinishReflectionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishReflection,
		arg.Reflection,
		arg.ReflectionError,
		arg.ReflectionSummary,
		arg.ReflectionOps,
		arg.ReflectionVersion,
		arg.WorkspaceID,
		arg.ID,
		arg.RequestedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRun = `-- name: GetRun :one
SELECT id, workspace_id, job_id, number, status, mode, fell_back, trigger, input, instructions, playbook_version,
  summary, outputs, error, turns, cost, ms_total, reflection, finished_at, reflection_requested_at
FROM runs WHERE workspace_id = $1 AND id = $2
`

type GetRunParams struct {
	WorkspaceID string
	ID          string
}

type GetRunRow struct {
	ID                    string
	WorkspaceID           string
	JobID                 string
	Number                int64
	Status                string
	Mode                  string
	FellBack              bool
	Trigger               string
	Input                 *string
	Instructions          *string
	PlaybookVersion       int64
	Summary               *string
	Outputs               *string
	Error                 *string
	Turns                 int64
	Cost                  int64
	MsTotal               *int64
	Reflection            string
	FinishedAt            *int64
	ReflectionRequestedAt *int64
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (GetRunRow, error) {
	row := q.db.QueryRowContext(ctx, getRun, arg.WorkspaceID, arg.ID)
	var i GetRunRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.JobID,
		&i.Number,
		&i.Status,
		&i.Mode,
		&i.FellBack,
		&i.Trigger,
		&i.Input,
		&i.Instructions,
		&i.PlaybookVersion,
		&i.Summary,
		&i.Outputs,
		&i.Error,
		&i.Turns,
		&i.Cost,
		&i.MsTotal,
		&i.Reflection,
		&i.FinishedAt,
		&i.ReflectionRequestedAt,
	)
	return i, err
}

const markPending = `-- name: MarkPending :execrows
UPDATE runs SET reflection = 'pending', reflection_error = NULL, reflection_requested_at = $1
WHERE workspace_id = $2 AND id = $3 AND reflection <> 'pending'
  AND status IN ('succeeded', 'failed', 'timed_out')
`

type MarkPendingParams struct {
	RequestedAt *int64
	WorkspaceID string
	ID          string
}

// A run can only be reflected on once it has ended, and never twice at the same time
func (q *Queries) MarkPending(ctx context.Context, arg MarkPendingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markPending, arg.RequestedAt, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recentRuns = `-- name: RecentRuns :many
SELECT id, number, status, mode, turns, cost, ms_total FROM runs
WHERE workspace_id = $1 AND job_id = $2 AND number < $3
  AND status IN ('succeeded', 'failed', 'timed_out')
ORDER BY number DESC LIMIT $4
`

type RecentRunsParams struct {
	WorkspaceID string
	JobID       string
	Number      int64
	MaxRuns     int32
}

type RecentRunsRow struct {
	ID      string
	Number  int64
	Status  string
	Mode    string
	Turns   int64
	Cost    int64
	MsTotal *int64
}

// The runs before this one show whether the job got faster and cheaper, and whether installs keep repeating
func (q *Queries) RecentRuns(ctx context.Context, arg RecentRunsParams) ([]RecentRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, recentRuns,
		arg.WorkspaceID,
		arg.JobID,
		arg.Number,
		arg.MaxRuns,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentRunsRow{}
	for rows.Next() {
		var i RecentRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Status,
			&i.Mode,
			&i.Turns,
			&i.Cost,
			&i.MsTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runEvents = `-- name: RunEvents :many
SELECT seq, type, ms, payload FROM run_events WHERE run_id = $1 ORDER BY seq
`

type RunEventsRow struct {
	Seq     int64
	Type    string
	Ms      *int64
	Payload string
}

// The run was loaded through its workspace first, and events are reached through it
func (q *Queries) RunEvents(ctx context.Context, runID string) ([]RunEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, runEvents, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunEventsRow{}
	for rows.Next() {
		var i RunEventsRow
		if err := rows.Scan(
			&i.Seq,
			&i.Type,
			&i.Ms,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumSpentSince = `-- name: SumSpentSince :one
SELECT CAST(COALESCE(SUM(cost + reflection_cost + verify_cost), 0) AS BIGINT) FROM runs
WHERE workspace_id = $1 AND queued_at >= $2
`

type SumSpentSinceParams struct {
	WorkspaceID string
	Since       int64
}

func (q *Queries) SumSpentSince(ctx context.Context, arg SumSpentSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumSpentSince, arg.WorkspaceID, arg.Since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
