// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package providersdb

import (
	"context"
)

const clearMissingModelSettings = `-- name: ClearMissingModelSettings :exec
DELETE FROM settings
WHERE settings.workspace_id = $1
  AND settings.key IN ('agentModelId', 'utilityModelId', 'reflectionModelId')
  AND settings.value NOT IN (SELECT '"' || m.id || '"' FROM models m WHERE m.workspace_id = $1)
`

// Default models are stored as JSON strings in settings, which no foreign key covers, so a deleted model's ID is removed from them here
func (q *Queries) ClearMissingModelSettings(ctx context.Context, workspaceID string) error {
	_, err := q.db.ExecContext(ctx, clearMissingModelSettings, workspaceID)
	return err
}

const createModel = `-- name: CreateModel :exec
INSERT INTO models (id, workspace_id, provider_id, model, label, price_in, price_out, price_cache_read, price_cache_write, context_window, caps, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateModelParams struct {
	ID              string
	WorkspaceID     string
	ProviderID      string
	Model           string
	Label           *string
	PriceIn         int64
	PriceOut        int64
	PriceCacheRead  int64
	PriceCacheWrite int64
	ContextWindow   int64
	Caps            string
	CreatedAt       int64
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) error {
	_, err := q.db.ExecContext(ctx, createModel,
		arg.ID,
		arg.WorkspaceID,
		arg.ProviderID,
		arg.Model,
		arg.Label,
		arg.PriceIn,
		arg.PriceOut,
		arg.PriceCacheRead,
		arg.PriceCacheWrite,
		arg.ContextWindow,
		arg.Caps,
		arg.CreatedAt,
	)
	return err
}

const createProvider = `-- name: CreateProvider :exec
INSERT INTO providers (id, workspace_id, name, kind, base_url, api_key_enc, key_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateProviderParams struct {
	ID          string
	WorkspaceID string
	Name        string
	Kind        string
	BaseUrl     *string
	ApiKeyEnc   []byte
	KeyID       *string
	CreatedAt   int64
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) error {
	_, err := q.db.ExecContext(ctx, createProvider,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Kind,
		arg.BaseUrl,
		arg.ApiKeyEnc,
		arg.KeyID,
		arg.CreatedAt,
	)
	return err
}

const createSyncedModel = `-- name: CreateSyncedModel :execrows
INSERT INTO models (id, workspace_id, provider_id, model, label, price_in, price_out, price_cache_read, price_cache_write, context_window, caps, synced, follow_catalog, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, TRUE, $12, $13)
ON CONFLICT (provider_id, model) DO NOTHING
`

type CreateSyncedModelParams struct {
	ID              string
	WorkspaceID     string
	ProviderID      string
	Model           string
	Label           *string
	PriceIn         int64
	PriceOut        int64
	PriceCacheRead  int64
	PriceCacheWrite int64
	ContextWindow   int64
	Caps            string
	FollowCatalog   bool
	CreatedAt       int64
}

// A sync of the same provider running at the same time may have added the model already, and its row is kept as that sync wrote it
func (q *Queries) CreateSyncedModel(ctx context.Context, arg CreateSyncedModelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createSyncedModel,
		arg.ID,
		arg.WorkspaceID,
		arg.ProviderID,
		arg.Model,
		arg.Label,
		arg.PriceIn,
		arg.PriceOut,
		arg.PriceCacheRead,
		arg.PriceCacheWrite,
		arg.ContextWindow,
		arg.Caps,
		arg.FollowCatalog,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteModel = `-- name: DeleteModel :execrows
DELETE FROM models WHERE workspace_id = $1 AND id = $2
`

type DeleteModelParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) DeleteModel(ctx context.Context, arg DeleteModelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteModel, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProvider = `-- name: DeleteProvider :execrows
DELETE FROM providers WHERE workspace_id = $1 AND id = $2
`

type DeleteProviderParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) DeleteProvider(ctx context.Context, arg DeleteProviderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProvider, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findModel = `-- name: FindModel :one
SELECT m.id FROM models m JOIN providers p ON p.id = m.provider_id
WHERE m.workspace_id = $1 AND p.kind = $2 AND m.model = $3
ORDER BY m.created_at LIMIT 1
`

type FindModelParams struct {
	WorkspaceID string
	Kind        string
	Model       string
}

func (q *Queries) FindModel(ctx context.Context, arg FindModelParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findModel, arg.WorkspaceID, arg.Kind, arg.Model)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getModel = `-- name: GetModel :one
SELECT m.id, m.provider_id, m.model, m.label, m.price_in, m.price_out, m.price_cache_read, m.price_cache_write, m.context_window, m.caps,
       m.enabled, m.synced, m.unlisted_at,
       p.name AS provider_name, p.kind AS provider_kind, p.base_url AS provider_base_url, p.api_key_enc AS provider_api_key_enc
FROM models m JOIN providers p ON p.id = m.provider_id
WHERE m.workspace_id = $1 AND m.id = $2
`

type GetModelParams struct {
	WorkspaceID string
	ID          string
}

type GetModelRow struct {
	ID                string
	ProviderID        string
	Model             string
	Label             *string
	PriceIn           int64
	PriceOut          int64
	PriceCacheRead    int64
	PriceCacheWrite   int64
	ContextWindow     int64
	Caps              string
	Enabled           bool
	Synced            bool
	UnlistedAt        *int64
	ProviderName      string
	ProviderKind      string
	ProviderBaseUrl   *string
	ProviderApiKeyEnc []byte
}

func (q *Queries) GetModel(ctx context.Context, arg GetModelParams) (GetModelRow, error) {
	row := q.db.QueryRowContext(ctx, getModel, arg.WorkspaceID, arg.ID)
	var i GetModelRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Model,
		&i.Label,
		&i.PriceIn,
		&i.PriceOut,
		&i.PriceCacheRead,
		&i.PriceCacheWrite,
		&i.ContextWindow,
		&i.Caps,
		&i.Enabled,
		&i.Synced,
		&i.UnlistedAt,
		&i.ProviderName,
		&i.ProviderKind,
		&i.ProviderBaseUrl,
		&i.ProviderApiKeyEnc,
	)
	return i, err
}

const getModelCatalog = `-- name: GetModelCatalog :one
SELECT data, fetched_at FROM model_catalog WHERE source = $1
`

type GetModelCatalogRow struct {
	Data      string
	FetchedAt int64
}

func (q *Queries) GetModelCatalog(ctx context.Context, source string) (GetModelCatalogRow, error) {
	row := q.db.QueryRowContext(ctx, getModelCatalog, source)
	var i GetModelCatalogRow
	err := row.Scan(&i.Data, &i.FetchedAt)
	return i, err
}

const getModelCatalogFetchedAt = `-- name: GetModelCatalogFetchedAt :one
SELECT fetched_at FROM model_catalog WHERE source = $1
`

func (q *Queries) GetModelCatalogFetchedAt(ctx context.Context, source string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getModelCatalogFetchedAt, source)
	var fetched_at int64
	err := row.Scan(&fetched_at)
	return fetched_at, err
}

const getProvider = `-- name: GetProvider :one
SELECT id, workspace_id, name, kind, base_url, api_key_enc, key_id, created_at, synced_at, sync_error FROM providers WHERE workspace_id = $1 AND id = $2
`

type GetProviderParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) GetProvider(ctx context.Context, arg GetProviderParams) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProvider, arg.WorkspaceID, arg.ID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Kind,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.KeyID,
		&i.CreatedAt,
		&i.SyncedAt,
		&i.SyncError,
	)
	return i, err
}

const listAllProviders = `-- name: ListAllProviders :many
SELECT id, workspace_id FROM providers ORDER BY created_at
`

type ListAllProvidersRow struct {
	ID          string
	WorkspaceID string
}

// unscoped: the catalog refresh syncs the providers of every workspace
func (q *Queries) ListAllProviders(ctx context.Context) ([]ListAllProvidersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllProvidersRow{}
	for rows.Next() {
		var i ListAllProvidersRow
		if err := rows.Scan(&i.ID, &i.WorkspaceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDefaultModelSettings = `-- name: ListDefaultModelSettings :many
SELECT key, value FROM settings
WHERE workspace_id = $1 AND key IN ('agentModelId', 'utilityModelId', 'reflectionModelId')
`

type ListDefaultModelSettingsRow struct {
	Key   string
	Value string
}

func (q *Queries) ListDefaultModelSettings(ctx context.Context, workspaceID string) ([]ListDefaultModelSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDefaultModelSettings, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDefaultModelSettingsRow{}
	for rows.Next() {
		var i ListDefaultModelSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderModels = `-- name: ListProviderModels :many
SELECT id, model, label, price_in, price_out, price_cache_read, price_cache_write, context_window, caps, synced, follow_catalog, unlisted_at FROM models
WHERE workspace_id = $1 AND provider_id = $2
`

type ListProviderModelsParams struct {
	WorkspaceID string
	ProviderID  string
}

type ListProviderModelsRow struct {
	ID              string
	Model           string
	Label           *string
	PriceIn         int64
	PriceOut        int64
	PriceCacheRead  int64
	PriceCacheWrite int64
	ContextWindow   int64
	Caps            string
	Synced          bool
	FollowCatalog   bool
	UnlistedAt      *int64
}

func (q *Queries) ListProviderModels(ctx context.Context, arg ListProviderModelsParams) ([]ListProviderModelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProviderModels, arg.WorkspaceID, arg.ProviderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProviderModelsRow{}
	for rows.Next() {
		var i ListProviderModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Model,
			&i.Label,
			&i.PriceIn,
			&i.PriceOut,
			&i.PriceCacheRead,
			&i.PriceCacheWrite,
			&i.ContextWindow,
			&i.Caps,
			&i.Synced,
			&i.FollowCatalog,
			&i.UnlistedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markModelListed = `-- name: MarkModelListed :exec
UPDATE models SET synced = TRUE, follow_catalog = $1, unlisted_at = NULL
WHERE workspace_id = $2 AND id = $3
`

type MarkModelListedParams struct {
	FollowCatalog bool
	WorkspaceID   string
	ID            string
}

// A model the source lists is synced from now on, even when an admin added it before the source listed it
// Leaving follow_catalog to the caller lets an admin turn following off while the model stays listed
func (q *Queries) MarkModelListed(ctx context.Context, arg MarkModelListedParams) error {
	_, err := q.db.ExecContext(ctx, markModelListed, arg.FollowCatalog, arg.WorkspaceID, arg.ID)
	return err
}

const markModelUnlisted = `-- name: MarkModelUnlisted :exec
UPDATE models SET unlisted_at = $1
WHERE workspace_id = $2 AND id = $3 AND unlisted_at IS NULL
`

type MarkModelUnlistedParams struct {
	UnlistedAt  *int64
	WorkspaceID string
	ID          string
}

func (q *Queries) MarkModelUnlisted(ctx context.Context, arg MarkModelUnlistedParams) error {
	_, err := q.db.ExecContext(ctx, markModelUnlisted, arg.UnlistedAt, arg.WorkspaceID, arg.ID)
	return err
}

const saveModelCatalog = `-- name: SaveModelCatalog :exec
INSERT INTO model_catalog (source, data, fetched_at) VALUES ($1, $2, $3)
ON CONFLICT (source) DO UPDATE SET data = excluded.data, fetched_at = excluded.fetched_at
WHERE excluded.fetched_at > model_catalog.fetched_at
`

type SaveModelCatalogParams struct {
	Source    string
	Data      string
	FetchedAt int64
}

// A replica that fetched an older document never replaces a newer one
func (q *Queries) SaveModelCatalog(ctx context.Context, arg SaveModelCatalogParams) error {
	_, err := q.db.ExecContext(ctx, saveModelCatalog, arg.Source, arg.Data, arg.FetchedAt)
	return err
}

const setModelEnabled = `-- name: SetModelEnabled :execrows
UPDATE models SET enabled = $1 WHERE workspace_id = $2 AND id = $3
`

type SetModelEnabledParams struct {
	Enabled     bool
	WorkspaceID string
	ID          string
}

func (q *Queries) SetModelEnabled(ctx context.Context, arg SetModelEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setModelEnabled, arg.Enabled, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setProviderModelsEnabled = `-- name: SetProviderModelsEnabled :execrows
UPDATE models SET enabled = $1 WHERE workspace_id = $2 AND provider_id = $3
`

type SetProviderModelsEnabledParams struct {
	Enabled     bool
	WorkspaceID string
	ProviderID  string
}

func (q *Queries) SetProviderModelsEnabled(ctx context.Context, arg SetProviderModelsEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setProviderModelsEnabled, arg.Enabled, arg.WorkspaceID, arg.ProviderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setProviderSync = `-- name: SetProviderSync :exec
UPDATE providers SET synced_at = $1, sync_error = $2
WHERE workspace_id = $3 AND id = $4
`

type SetProviderSyncParams struct {
	SyncedAt    *int64
	SyncError   *string
	WorkspaceID string
	ID          string
}

func (q *Queries) SetProviderSync(ctx context.Context, arg SetProviderSyncParams) error {
	_, err := q.db.ExecContext(ctx, setProviderSync,
		arg.SyncedAt,
		arg.SyncError,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const updateModel = `-- name: UpdateModel :execrows
UPDATE models SET label = $1, price_in = $2, price_out = $3,
  price_cache_read = $4, price_cache_write = $5,
  context_window = $6, caps = $7, follow_catalog = $8
WHERE workspace_id = $9 AND id = $10
`

type UpdateModelParams struct {
	Label           *string
	PriceIn         int64
	PriceOut        int64
	PriceCacheRead  int64
	PriceCacheWrite int64
	ContextWindow   int64
	Caps            string
	FollowCatalog   bool
	WorkspaceID     string
	ID              string
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateModel,
		arg.Label,
		arg.PriceIn,
		arg.PriceOut,
		arg.PriceCacheRead,
		arg.PriceCacheWrite,
		arg.ContextWindow,
		arg.Caps,
		arg.FollowCatalog,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateModelMetadata = `-- name: UpdateModelMetadata :exec
UPDATE models SET label = $1, price_in = $2, price_out = $3,
  price_cache_read = $4, price_cache_write = $5,
  context_window = $6, caps = $7
WHERE workspace_id = $8 AND id = $9 AND follow_catalog
`

type UpdateModelMetadataParams struct {
	Label           *string
	PriceIn         int64
	PriceOut        int64
	PriceCacheRead  int64
	PriceCacheWrite int64
	ContextWindow   int64
	Caps            string
	WorkspaceID     string
	ID              string
}

// A sync refreshes the metadata of models that follow the catalog, leaving the label, prices and capabilities an admin set alone
func (q *Queries) UpdateModelMetadata(ctx context.Context, arg UpdateModelMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateModelMetadata,
		arg.Label,
		arg.PriceIn,
		arg.PriceOut,
		arg.PriceCacheRead,
		arg.PriceCacheWrite,
		arg.ContextWindow,
		arg.Caps,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const updateProvider = `-- name: UpdateProvider :execrows
UPDATE providers SET name = $1, base_url = $2
WHERE workspace_id = $3 AND id = $4
`

type UpdateProviderParams struct {
	Name        string
	BaseUrl     *string
	WorkspaceID string
	ID          string
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProvider,
		arg.Name,
		arg.BaseUrl,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProviderKey = `-- name: UpdateProviderKey :execrows
UPDATE providers SET api_key_enc = $1, key_id = $2
WHERE workspace_id = $3 AND id = $4
`

type UpdateProviderKeyParams struct {
	ApiKeyEnc   []byte
	KeyID       *string
	WorkspaceID string
	ID          string
}

func (q *Queries) UpdateProviderKey(ctx context.Context, arg UpdateProviderKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProviderKey,
		arg.ApiKeyEnc,
		arg.KeyID,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
