// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package skillsdb

import (
	"context"
)

const addJobSkill = `-- name: AddJobSkill :exec
INSERT INTO job_skills (job_id, skill_id) VALUES ($1, $2)
`

type AddJobSkillParams struct {
	JobID   string
	SkillID string
}

func (q *Queries) AddJobSkill(ctx context.Context, arg AddJobSkillParams) error {
	_, err := q.db.ExecContext(ctx, addJobSkill, arg.JobID, arg.SkillID)
	return err
}

const clearJobSkills = `-- name: ClearJobSkills :exec
DELETE FROM job_skills WHERE job_id = $1
`

func (q *Queries) ClearJobSkills(ctx context.Context, jobID string) error {
	_, err := q.db.ExecContext(ctx, clearJobSkills, jobID)
	return err
}

const countSkillJobs = `-- name: CountSkillJobs :one
SELECT COUNT(*) FROM job_skills js JOIN skills s ON s.id = js.skill_id WHERE s.workspace_id = $1 AND js.skill_id = $2
`

type CountSkillJobsParams struct {
	WorkspaceID string
	SkillID     string
}

func (q *Queries) CountSkillJobs(ctx context.Context, arg CountSkillJobsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSkillJobs, arg.WorkspaceID, arg.SkillID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSkill = `-- name: CreateSkill :exec
INSERT INTO skills (id, workspace_id, name, description, content_hash, files, file_count, size, archive_size, source_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11, $11)
`

type CreateSkillParams struct {
	ID          string
	WorkspaceID string
	Name        string
	Description string
	ContentHash string
	Files       string
	FileCount   int64
	Size        int64
	ArchiveSize int64
	SourceUrl   *string
	Now         int64
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) error {
	_, err := q.db.ExecContext(ctx, createSkill,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.ContentHash,
		arg.Files,
		arg.FileCount,
		arg.Size,
		arg.ArchiveSize,
		arg.SourceUrl,
		arg.Now,
	)
	return err
}

const deleteSkill = `-- name: DeleteSkill :execrows
DELETE FROM skills WHERE workspace_id = $1 AND id = $2
`

type DeleteSkillParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) DeleteSkill(ctx context.Context, arg DeleteSkillParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSkill, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSkill = `-- name: GetSkill :one
SELECT id, workspace_id, name, description, content_hash, files, file_count, size, archive_size, source_url, created_at, updated_at FROM skills WHERE workspace_id = $1 AND id = $2
`

type GetSkillParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) GetSkill(ctx context.Context, arg GetSkillParams) (Skill, error) {
	row := q.db.QueryRowContext(ctx, getSkill, arg.WorkspaceID, arg.ID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.ContentHash,
		&i.Files,
		&i.FileCount,
		&i.Size,
		&i.ArchiveSize,
		&i.SourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillByName = `-- name: GetSkillByName :one
SELECT id, workspace_id, name, description, content_hash, files, file_count, size, archive_size, source_url, created_at, updated_at FROM skills WHERE workspace_id = $1 AND name = $2
`

type GetSkillByNameParams struct {
	WorkspaceID string
	Name        string
}

func (q *Queries) GetSkillByName(ctx context.Context, arg GetSkillByNameParams) (Skill, error) {
	row := q.db.QueryRowContext(ctx, getSkillByName, arg.WorkspaceID, arg.Name)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.ContentHash,
		&i.Files,
		&i.FileCount,
		&i.Size,
		&i.ArchiveSize,
		&i.SourceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobSkills = `-- name: ListJobSkills :many
SELECT s.id, s.name, s.description, s.size
FROM job_skills js JOIN skills s ON s.id = js.skill_id
WHERE s.workspace_id = $1 AND js.job_id = $2 ORDER BY s.name
`

type ListJobSkillsParams struct {
	WorkspaceID string
	JobID       string
}

type ListJobSkillsRow struct {
	ID          string
	Name        string
	Description string
	Size        int64
}

func (q *Queries) ListJobSkills(ctx context.Context, arg ListJobSkillsParams) ([]ListJobSkillsRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobSkills, arg.WorkspaceID, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobSkillsRow{}
	for rows.Next() {
		var i ListJobSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillCatalog = `-- name: ListSkillCatalog :many
SELECT id, name, description, size FROM skills WHERE workspace_id = $1 ORDER BY name
`

type ListSkillCatalogRow struct {
	ID          string
	Name        string
	Description string
	Size        int64
}

func (q *Queries) ListSkillCatalog(ctx context.Context, workspaceID string) ([]ListSkillCatalogRow, error) {
	rows, err := q.db.QueryContext(ctx, listSkillCatalog, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSkillCatalogRow{}
	for rows.Next() {
		var i ListSkillCatalogRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillIDsOfWorkspace = `-- name: ListSkillIDsOfWorkspace :many
SELECT id FROM skills WHERE workspace_id = $1
`

func (q *Queries) ListSkillIDsOfWorkspace(ctx context.Context, workspaceID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSkillIDsOfWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceSkill = `-- name: ReplaceSkill :execrows
UPDATE skills SET description = $1, content_hash = $2, files = $3, file_count = $4,
  size = $5, archive_size = $6, source_url = $7, updated_at = $8
WHERE workspace_id = $9 AND id = $10 AND content_hash = $11
`

type ReplaceSkillParams struct {
	Description string
	ContentHash string
	Files       string
	FileCount   int64
	Size        int64
	ArchiveSize int64
	SourceUrl   *string
	UpdatedAt   int64
	WorkspaceID string
	ID          string
	OldHash     string
}

// The update only lands on the version the upload replaced, so two concurrent uploads can't leave a row pointing at a deleted blob
func (q *Queries) ReplaceSkill(ctx context.Context, arg ReplaceSkillParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, replaceSkill,
		arg.Description,
		arg.ContentHash,
		arg.Files,
		arg.FileCount,
		arg.Size,
		arg.ArchiveSize,
		arg.SourceUrl,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.ID,
		arg.OldHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSkillSource = `-- name: SetSkillSource :execrows
UPDATE skills SET source_url = $1, updated_at = $2 WHERE workspace_id = $3 AND id = $4
`

type SetSkillSourceParams struct {
	SourceUrl   *string
	UpdatedAt   int64
	WorkspaceID string
	ID          string
}

func (q *Queries) SetSkillSource(ctx context.Context, arg SetSkillSourceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSkillSource,
		arg.SourceUrl,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
