// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package authdb

import (
	"context"
)

const claimGitHubName = `-- name: ClaimGitHubName :one
INSERT INTO kv (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = kv.value
RETURNING value
`

type ClaimGitHubNameParams struct {
	Key   string
	Value string
}

// unscoped: an instance-wide key-value row whose key names a GitHub username or organization
// The first claim stores its ID and every later one leaves it, so the query returns the ID that claimed the name first
func (q *Queries) ClaimGitHubName(ctx context.Context, arg ClaimGitHubNameParams) (string, error) {
	row := q.db.QueryRowContext(ctx, claimGitHubName, arg.Key, arg.Value)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getUser = `-- name: GetUser :one
SELECT id, subject, email, name, created_at, last_login_at, picture, issuer, is_admin, email_verified, disabled_at, last_workspace_id FROM users WHERE id = $1
`

// unscoped: users are instance-wide
func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.Picture,
		&i.Issuer,
		&i.IsAdmin,
		&i.EmailVerified,
		&i.DisabledAt,
		&i.LastWorkspaceID,
	)
	return i, err
}

const setUserDisabled = `-- name: SetUserDisabled :execrows
UPDATE users SET disabled_at = $1 WHERE id = $2
`

type SetUserDisabledParams struct {
	DisabledAt *int64
	ID         string
}

// unscoped: users are instance-wide, and only instance admins deactivate them
func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setUserDisabled, arg.DisabledAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, issuer, subject, email, email_verified, name, picture, is_admin, created_at, last_login_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $9)
ON CONFLICT (issuer, subject) DO UPDATE SET email = excluded.email, email_verified = excluded.email_verified, name = excluded.name, picture = excluded.picture, is_admin = excluded.is_admin, last_login_at = excluded.last_login_at
RETURNING id, subject, email, name, created_at, last_login_at, picture, issuer, is_admin, email_verified, disabled_at, last_workspace_id
`

type UpsertUserParams struct {
	ID            string
	Issuer        string
	Subject       string
	Email         *string
	EmailVerified bool
	Name          *string
	Picture       *string
	IsAdmin       bool
	Now           int64
}

// unscoped: users are instance-wide and keyed by the issuer and subject of the account they sign in with
// Whether the email address is verified and whether the user is an instance admin come from the sign-in provider every time
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.ID,
		arg.Issuer,
		arg.Subject,
		arg.Email,
		arg.EmailVerified,
		arg.Name,
		arg.Picture,
		arg.IsAdmin,
		arg.Now,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.Picture,
		&i.Issuer,
		&i.IsAdmin,
		&i.EmailVerified,
		&i.DisabledAt,
		&i.LastWorkspaceID,
	)
	return i, err
}
