// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package authdb

import (
	"context"
)

const claimGitHubName = `-- name: ClaimGitHubName :one
INSERT INTO kv (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = kv.value
RETURNING value
`

type ClaimGitHubNameParams struct {
	Key   string
	Value string
}

// unscoped: an instance-wide key-value row whose key names a GitHub username or organization
// The first claim stores its ID and every later one leaves it, so the query returns the ID that claimed the name first
func (q *Queries) ClaimGitHubName(ctx context.Context, arg ClaimGitHubNameParams) (string, error) {
	row := q.db.QueryRowContext(ctx, claimGitHubName, arg.Key, arg.Value)
	var value string
	err := row.Scan(&value)
	return value, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, created_at, expires_at) VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	TokenHash string
	UserID    string
	CreatedAt int64
	ExpiresAt int64
}

// unscoped: sessions belong to users, who are instance-wide
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= $1
`

// unscoped: sessions belong to users, who are instance-wide
func (q *Queries) DeleteExpiredSessions(ctx context.Context, now int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, now)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

// unscoped: sessions belong to users, who are instance-wide
func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

// unscoped: sessions belong to users, who are instance-wide
func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT user_id FROM sessions WHERE token_hash = $1 AND expires_at > $2
`

type GetSessionUserParams struct {
	TokenHash string
	Now       int64
}

// unscoped: sessions belong to users, who are instance-wide
func (q *Queries) GetSessionUser(ctx context.Context, arg GetSessionUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSessionUser, arg.TokenHash, arg.Now)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getUser = `-- name: GetUser :one
SELECT id, issuer, subject, email, email_verified, name, picture, is_admin, disabled_at, last_workspace_id, created_at, last_login_at FROM users WHERE id = $1
`

// unscoped: users are instance-wide
func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.Picture,
		&i.IsAdmin,
		&i.DisabledAt,
		&i.LastWorkspaceID,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const setUserDisabled = `-- name: SetUserDisabled :execrows
UPDATE users SET disabled_at = $1 WHERE id = $2
`

type SetUserDisabledParams struct {
	DisabledAt *int64
	ID         string
}

// unscoped: users are instance-wide, and only instance admins deactivate them
func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setUserDisabled, arg.DisabledAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, issuer, subject, email, email_verified, name, picture, is_admin, created_at, last_login_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $9)
ON CONFLICT (issuer, subject) DO UPDATE SET email = excluded.email, email_verified = excluded.email_verified, name = excluded.name, picture = excluded.picture, is_admin = excluded.is_admin, last_login_at = excluded.last_login_at
RETURNING id, issuer, subject, email, email_verified, name, picture, is_admin, disabled_at, last_workspace_id, created_at, last_login_at
`

type UpsertUserParams struct {
	ID            string
	Issuer        string
	Subject       string
	Email         *string
	EmailVerified bool
	Name          *string
	Picture       *string
	IsAdmin       bool
	Now           int64
}

// unscoped: users are instance-wide and keyed by the issuer and subject of the account they sign in with
// Whether the email address is verified and whether the user is an instance admin come from the sign-in provider every time
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.ID,
		arg.Issuer,
		arg.Subject,
		arg.Email,
		arg.EmailVerified,
		arg.Name,
		arg.Picture,
		arg.IsAdmin,
		arg.Now,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.Picture,
		&i.IsAdmin,
		&i.DisabledAt,
		&i.LastWorkspaceID,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
