// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package playbookdb

import (
	"context"
)

const addStats = `-- name: AddStats :exec
INSERT INTO playbook_stats (job_id, kind, name, hits, calls, failures, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (job_id, kind, name) DO UPDATE SET
  hits = playbook_stats.hits + excluded.hits,
  calls = playbook_stats.calls + excluded.calls,
  failures = playbook_stats.failures + excluded.failures,
  updated_at = excluded.updated_at
`

type AddStatsParams struct {
	JobID     string
	Kind      string
	Name      string
	Hits      int64
	Calls     int64
	Failures  int64
	UpdatedAt int64
}

// Counters only ever grow, so concurrent runs of one job add up instead of overwriting each other
func (q *Queries) AddStats(ctx context.Context, arg AddStatsParams) error {
	_, err := q.db.ExecContext(ctx, addStats,
		arg.JobID,
		arg.Kind,
		arg.Name,
		arg.Hits,
		arg.Calls,
		arg.Failures,
		arg.UpdatedAt,
	)
	return err
}

const getVersion = `-- name: GetVersion :one
SELECT job_id, version, content, ops, summary, dockerfile_hash, author, author_user_id, source_run_id, created_at FROM playbook_versions WHERE job_id = $1 AND version = $2
`

type GetVersionParams struct {
	JobID   string
	Version int64
}

func (q *Queries) GetVersion(ctx context.Context, arg GetVersionParams) (PlaybookVersion, error) {
	row := q.db.QueryRowContext(ctx, getVersion, arg.JobID, arg.Version)
	var i PlaybookVersion
	err := row.Scan(
		&i.JobID,
		&i.Version,
		&i.Content,
		&i.Ops,
		&i.Summary,
		&i.DockerfileHash,
		&i.Author,
		&i.AuthorUserID,
		&i.SourceRunID,
		&i.CreatedAt,
	)
	return i, err
}

const insertVersion = `-- name: InsertVersion :exec
INSERT INTO playbook_versions (job_id, version, content, ops, summary, dockerfile_hash, author, author_user_id, source_run_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertVersionParams struct {
	JobID          string
	Version        int64
	Content        string
	Ops            *string
	Summary        *string
	DockerfileHash *string
	Author         string
	AuthorUserID   *string
	SourceRunID    *string
	CreatedAt      int64
}

func (q *Queries) InsertVersion(ctx context.Context, arg InsertVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertVersion,
		arg.JobID,
		arg.Version,
		arg.Content,
		arg.Ops,
		arg.Summary,
		arg.DockerfileHash,
		arg.Author,
		arg.AuthorUserID,
		arg.SourceRunID,
		arg.CreatedAt,
	)
	return err
}

const latestVersion = `-- name: LatestVersion :one
SELECT CAST(COALESCE(MAX(version), 0) AS BIGINT) FROM playbook_versions WHERE job_id = $1
`

func (q *Queries) LatestVersion(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestVersion, jobID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listStats = `-- name: ListStats :many
SELECT kind, name, hits, calls, failures FROM playbook_stats WHERE job_id = $1
`

type ListStatsRow struct {
	Kind     string
	Name     string
	Hits     int64
	Calls    int64
	Failures int64
}

func (q *Queries) ListStats(ctx context.Context, jobID string) ([]ListStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStats, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStatsRow{}
	for rows.Next() {
		var i ListStatsRow
		if err := rows.Scan(
			&i.Kind,
			&i.Name,
			&i.Hits,
			&i.Calls,
			&i.Failures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGraduatedVersion = `-- name: SetGraduatedVersion :exec
UPDATE jobs SET graduated_version = $1 WHERE workspace_id = $2 AND id = $3
`

type SetGraduatedVersionParams struct {
	Version     *int64
	WorkspaceID string
	JobID       string
}

func (q *Queries) SetGraduatedVersion(ctx context.Context, arg SetGraduatedVersionParams) error {
	_, err := q.db.ExecContext(ctx, setGraduatedVersion, arg.Version, arg.WorkspaceID, arg.JobID)
	return err
}

const setJobPlaybookVersion = `-- name: SetJobPlaybookVersion :execrows
UPDATE jobs SET playbook_version = $1, updated_at = $2 WHERE workspace_id = $3 AND id = $4
`

type SetJobPlaybookVersionParams struct {
	Version     int64
	UpdatedAt   int64
	WorkspaceID string
	JobID       string
}

func (q *Queries) SetJobPlaybookVersion(ctx context.Context, arg SetJobPlaybookVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setJobPlaybookVersion,
		arg.Version,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.JobID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
