// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package jobsdb

import (
	"context"
)

const archiveJob = `-- name: ArchiveJob :execrows
UPDATE jobs SET archived_at = $1, next_run_at = NULL
WHERE workspace_id = $2 AND id = $3 AND archived_at IS NULL
`

type ArchiveJobParams struct {
	ArchivedAt  *int64
	WorkspaceID string
	ID          string
}

func (q *Queries) ArchiveJob(ctx context.Context, arg ArchiveJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveJob, arg.ArchivedAt, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createJob = `-- name: CreateJob :exec
INSERT INTO jobs (id, workspace_id, name, instruction, spec, model_id, image, network, allowed_domains, allow_private_network, run_as_root, limits, self_improve, graduate, concurrency, cron, timezone, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $19)
`

type CreateJobParams struct {
	ID                  string
	WorkspaceID         string
	Name                string
	Instruction         string
	Spec                string
	ModelID             *string
	Image               *string
	Network             string
	AllowedDomains      string
	AllowPrivateNetwork bool
	RunAsRoot           bool
	Limits              string
	SelfImprove         bool
	Graduate            bool
	Concurrency         string
	Cron                *string
	Timezone            *string
	CreatedBy           *string
	CreatedAt           int64
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.ExecContext(ctx, createJob,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Instruction,
		arg.Spec,
		arg.ModelID,
		arg.Image,
		arg.Network,
		arg.AllowedDomains,
		arg.AllowPrivateNetwork,
		arg.RunAsRoot,
		arg.Limits,
		arg.SelfImprove,
		arg.Graduate,
		arg.Concurrency,
		arg.Cron,
		arg.Timezone,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE workspace_id = $1 AND id = $2
`

type DeleteJobParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) DeleteJob(ctx context.Context, arg DeleteJobParams) error {
	_, err := q.db.ExecContext(ctx, deleteJob, arg.WorkspaceID, arg.ID)
	return err
}

const deleteState = `-- name: DeleteState :execrows
DELETE FROM job_state WHERE job_id = $1 AND key = $2
`

type DeleteStateParams struct {
	JobID string
	Key   string
}

func (q *Queries) DeleteState(ctx context.Context, arg DeleteStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteState, arg.JobID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getJob = `-- name: GetJob :one
SELECT id, workspace_id, name, instruction, spec, spec_overrides, model_id, image, network, run_as_root, limits, self_improve, playbook_version, concurrency, cron, timezone, next_run_at, webhook_token_hash, run_counter, created_by, created_at, updated_at, archived_at, graduated_version, allowed_domains, allow_private_network, graduate FROM jobs WHERE workspace_id = $1 AND id = $2 AND archived_at IS NULL
`

type GetJobParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, arg.WorkspaceID, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Instruction,
		&i.Spec,
		&i.SpecOverrides,
		&i.ModelID,
		&i.Image,
		&i.Network,
		&i.RunAsRoot,
		&i.Limits,
		&i.SelfImprove,
		&i.PlaybookVersion,
		&i.Concurrency,
		&i.Cron,
		&i.Timezone,
		&i.NextRunAt,
		&i.WebhookTokenHash,
		&i.RunCounter,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.GraduatedVersion,
		&i.AllowedDomains,
		&i.AllowPrivateNetwork,
		&i.Graduate,
	)
	return i, err
}

const getJobUnscoped = `-- name: GetJobUnscoped :one
SELECT id, workspace_id, name, instruction, spec, spec_overrides, model_id, image, network, run_as_root, limits, self_improve, playbook_version, concurrency, cron, timezone, next_run_at, webhook_token_hash, run_counter, created_by, created_at, updated_at, archived_at, graduated_version, allowed_domains, allow_private_network, graduate FROM jobs WHERE id = $1
`

// unscoped: used by the job actor and webhooks, which are keyed by the globally unique job ID and then act within the job's workspace
func (q *Queries) GetJobUnscoped(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobUnscoped, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Instruction,
		&i.Spec,
		&i.SpecOverrides,
		&i.ModelID,
		&i.Image,
		&i.Network,
		&i.RunAsRoot,
		&i.Limits,
		&i.SelfImprove,
		&i.PlaybookVersion,
		&i.Concurrency,
		&i.Cron,
		&i.Timezone,
		&i.NextRunAt,
		&i.WebhookTokenHash,
		&i.RunCounter,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.GraduatedVersion,
		&i.AllowedDomains,
		&i.AllowPrivateNetwork,
		&i.Graduate,
	)
	return i, err
}

const getLastRun = `-- name: GetLastRun :one
SELECT id, number, status, queued_at FROM runs
WHERE workspace_id = $1 AND job_id = $2
ORDER BY queued_at DESC, id DESC LIMIT 1
`

type GetLastRunParams struct {
	WorkspaceID string
	JobID       string
}

type GetLastRunRow struct {
	ID       string
	Number   int64
	Status   string
	QueuedAt int64
}

func (q *Queries) GetLastRun(ctx context.Context, arg GetLastRunParams) (GetLastRunRow, error) {
	row := q.db.QueryRowContext(ctx, getLastRun, arg.WorkspaceID, arg.JobID)
	var i GetLastRunRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Status,
		&i.QueuedAt,
	)
	return i, err
}

const getState = `-- name: GetState :one
SELECT value, updated_at FROM job_state WHERE job_id = $1 AND key = $2
`

type GetStateParams struct {
	JobID string
	Key   string
}

type GetStateRow struct {
	Value     string
	UpdatedAt int64
}

func (q *Queries) GetState(ctx context.Context, arg GetStateParams) (GetStateRow, error) {
	row := q.db.QueryRowContext(ctx, getState, arg.JobID, arg.Key)
	var i GetStateRow
	err := row.Scan(&i.Value, &i.UpdatedAt)
	return i, err
}

const listActiveRunsForJob = `-- name: ListActiveRunsForJob :many
SELECT id, status FROM runs WHERE workspace_id = $1 AND job_id = $2 AND status IN ('queued', 'provisioning', 'running', 'verifying')
`

type ListActiveRunsForJobParams struct {
	WorkspaceID string
	JobID       string
}

type ListActiveRunsForJobRow struct {
	ID     string
	Status string
}

func (q *Queries) ListActiveRunsForJob(ctx context.Context, arg ListActiveRunsForJobParams) ([]ListActiveRunsForJobRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRunsForJob, arg.WorkspaceID, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveRunsForJobRow{}
	for rows.Next() {
		var i ListActiveRunsForJobRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobIDs = `-- name: ListJobIDs :many
SELECT id FROM jobs WHERE workspace_id = $1
`

func (q *Queries) ListJobIDs(ctx context.Context, workspaceID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listJobIDs, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listState = `-- name: ListState :many
SELECT key, value, updated_at FROM job_state WHERE job_id = $1 ORDER BY key
`

type ListStateRow struct {
	Key       string
	Value     string
	UpdatedAt int64
}

func (q *Queries) ListState(ctx context.Context, jobID string) ([]ListStateRow, error) {
	rows, err := q.db.QueryContext(ctx, listState, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStateRow{}
	for rows.Next() {
		var i ListStateRow
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStateForWrite = `-- name: LockStateForWrite :exec
UPDATE jobs SET updated_at = updated_at WHERE id = $1
`

// Writes to one job's state take turns on the job's row, so concurrent writes can't together pass a limit that each of them checks alone
// unscoped: a state store belongs to a job its caller already reached through its workspace
func (q *Queries) LockStateForWrite(ctx context.Context, jobID string) error {
	_, err := q.db.ExecContext(ctx, lockStateForWrite, jobID)
	return err
}

const nextRunNumber = `-- name: NextRunNumber :one
UPDATE jobs SET run_counter = run_counter + 1 WHERE workspace_id = $1 AND id = $2 RETURNING run_counter
`

type NextRunNumberParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) NextRunNumber(ctx context.Context, arg NextRunNumberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextRunNumber, arg.WorkspaceID, arg.ID)
	var run_counter int64
	err := row.Scan(&run_counter)
	return run_counter, err
}

const recentScriptedRuns = `-- name: RecentScriptedRuns :many
SELECT fell_back FROM runs
WHERE workspace_id = $1 AND job_id = $2 AND mode = 'scripted'
  AND playbook_version >= $3 AND status IN ('succeeded', 'failed', 'timed_out')
ORDER BY number DESC LIMIT 2
`

type RecentScriptedRunsParams struct {
	WorkspaceID  string
	JobID        string
	SinceVersion int64
}

// Two fallbacks in a row since the job graduated demote it to Assisted until it graduates again
func (q *Queries) RecentScriptedRuns(ctx context.Context, arg RecentScriptedRunsParams) ([]bool, error) {
	rows, err := q.db.QueryContext(ctx, recentScriptedRuns, arg.WorkspaceID, arg.JobID, arg.SinceVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []bool{}
	for rows.Next() {
		var fell_back bool
		if err := rows.Scan(&fell_back); err != nil {
			return nil, err
		}
		items = append(items, fell_back)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNextRunAt = `-- name: SetNextRunAt :exec
UPDATE jobs SET next_run_at = $1 WHERE workspace_id = $2 AND id = $3
`

type SetNextRunAtParams struct {
	NextRunAt   *int64
	WorkspaceID string
	ID          string
}

func (q *Queries) SetNextRunAt(ctx context.Context, arg SetNextRunAtParams) error {
	_, err := q.db.ExecContext(ctx, setNextRunAt, arg.NextRunAt, arg.WorkspaceID, arg.ID)
	return err
}

const setState = `-- name: SetState :exec
INSERT INTO job_state (job_id, key, value, updated_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (job_id, key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type SetStateParams struct {
	JobID     string
	Key       string
	Value     string
	UpdatedAt int64
}

func (q *Queries) SetState(ctx context.Context, arg SetStateParams) error {
	_, err := q.db.ExecContext(ctx, setState,
		arg.JobID,
		arg.Key,
		arg.Value,
		arg.UpdatedAt,
	)
	return err
}

const setWebhookTokenHash = `-- name: SetWebhookTokenHash :exec
UPDATE jobs SET webhook_token_hash = $1, updated_at = $2 WHERE workspace_id = $3 AND id = $4
`

type SetWebhookTokenHashParams struct {
	WebhookTokenHash *string
	UpdatedAt        int64
	WorkspaceID      string
	ID               string
}

func (q *Queries) SetWebhookTokenHash(ctx context.Context, arg SetWebhookTokenHashParams) error {
	_, err := q.db.ExecContext(ctx, setWebhookTokenHash,
		arg.WebhookTokenHash,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const stateEntrySize = `-- name: StateEntrySize :one
SELECT CAST(OCTET_LENGTH(key) + OCTET_LENGTH(value) AS BIGINT) AS size FROM job_state WHERE job_id = $1 AND key = $2
`

type StateEntrySizeParams struct {
	JobID string
	Key   string
}

// The size of one key and its value, counted like StateUsage
func (q *Queries) StateEntrySize(ctx context.Context, arg StateEntrySizeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, stateEntrySize, arg.JobID, arg.Key)
	var size int64
	err := row.Scan(&size)
	return size, err
}

const stateUsage = `-- name: StateUsage :one
SELECT COUNT(*) AS keys, CAST(COALESCE(SUM(OCTET_LENGTH(key) + OCTET_LENGTH(value)), 0) AS BIGINT) AS bytes FROM job_state WHERE job_id = $1
`

type StateUsageRow struct {
	Keys  int64
	Bytes int64
}

// Sizes are counted in bytes like Go's len, since LENGTH counts characters
func (q *Queries) StateUsage(ctx context.Context, jobID string) (StateUsageRow, error) {
	row := q.db.QueryRowContext(ctx, stateUsage, jobID)
	var i StateUsageRow
	err := row.Scan(&i.Keys, &i.Bytes)
	return i, err
}

const updateJob = `-- name: UpdateJob :execrows
UPDATE jobs SET name = $1, instruction = $2, spec = $3,
  model_id = $4, image = $5, network = $6,
  allowed_domains = $7, allow_private_network = $8, run_as_root = $9,
  limits = $10, self_improve = $11, graduate = $12, concurrency = $13,
  cron = $14, timezone = $15, updated_at = $16
WHERE workspace_id = $17 AND id = $18 AND archived_at IS NULL AND updated_at = $19
`

type UpdateJobParams struct {
	Name                string
	Instruction         string
	Spec                string
	ModelID             *string
	Image               *string
	Network             string
	AllowedDomains      string
	AllowPrivateNetwork bool
	RunAsRoot           bool
	Limits              string
	SelfImprove         bool
	Graduate            bool
	Concurrency         string
	Cron                *string
	Timezone            *string
	UpdatedAt           int64
	WorkspaceID         string
	ID                  string
	ReadUpdatedAt       int64
}

// Only a job still at the updated_at it was read with is written, so a concurrent change is detected instead of overwritten
func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateJob,
		arg.Name,
		arg.Instruction,
		arg.Spec,
		arg.ModelID,
		arg.Image,
		arg.Network,
		arg.AllowedDomains,
		arg.AllowPrivateNetwork,
		arg.RunAsRoot,
		arg.Limits,
		arg.SelfImprove,
		arg.Graduate,
		arg.Concurrency,
		arg.Cron,
		arg.Timezone,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.ID,
		arg.ReadUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
