// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package jobsdb

import (
	"context"
)

const archiveJob = `-- name: ArchiveJob :execrows
UPDATE jobs SET archived_at = $1, enabled = FALSE, next_run_at = NULL
WHERE workspace_id = $2 AND id = $3 AND archived_at IS NULL
`

type ArchiveJobParams struct {
	ArchivedAt  *int64
	WorkspaceID string
	ID          string
}

func (q *Queries) ArchiveJob(ctx context.Context, arg ArchiveJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveJob, arg.ArchivedAt, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countState = `-- name: CountState :one
SELECT COUNT(*) FROM job_state WHERE job_id = $1
`

func (q *Queries) CountState(ctx context.Context, jobID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countState, jobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :exec
INSERT INTO jobs (id, workspace_id, name, instruction, spec, spec_overrides, model_id, image, network, allowed_domains, allow_private_network, run_as_root, limits, self_improve, mode_pin, concurrency, cron, timezone, enabled, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $21)
`

type CreateJobParams struct {
	ID                  string
	WorkspaceID         string
	Name                string
	Instruction         string
	Spec                string
	SpecOverrides       string
	ModelID             *string
	Image               *string
	Network             string
	AllowedDomains      string
	AllowPrivateNetwork bool
	RunAsRoot           bool
	Limits              string
	SelfImprove         bool
	ModePin             *string
	Concurrency         string
	Cron                *string
	Timezone            *string
	Enabled             bool
	CreatedBy           *string
	CreatedAt           int64
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.ExecContext(ctx, createJob,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Instruction,
		arg.Spec,
		arg.SpecOverrides,
		arg.ModelID,
		arg.Image,
		arg.Network,
		arg.AllowedDomains,
		arg.AllowPrivateNetwork,
		arg.RunAsRoot,
		arg.Limits,
		arg.SelfImprove,
		arg.ModePin,
		arg.Concurrency,
		arg.Cron,
		arg.Timezone,
		arg.Enabled,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const deleteState = `-- name: DeleteState :execrows
DELETE FROM job_state WHERE job_id = $1 AND key = $2
`

type DeleteStateParams struct {
	JobID string
	Key   string
}

func (q *Queries) DeleteState(ctx context.Context, arg DeleteStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteState, arg.JobID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getJob = `-- name: GetJob :one
SELECT id, workspace_id, name, instruction, spec, spec_overrides, model_id, image, network, run_as_root, limits, self_improve, mode_pin, playbook_version, concurrency, cron, timezone, next_run_at, webhook_token_hash, enabled, run_counter, created_by, created_at, updated_at, archived_at, graduated_version, allowed_domains, allow_private_network FROM jobs WHERE workspace_id = $1 AND id = $2 AND archived_at IS NULL
`

type GetJobParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, arg.WorkspaceID, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Instruction,
		&i.Spec,
		&i.SpecOverrides,
		&i.ModelID,
		&i.Image,
		&i.Network,
		&i.RunAsRoot,
		&i.Limits,
		&i.SelfImprove,
		&i.ModePin,
		&i.PlaybookVersion,
		&i.Concurrency,
		&i.Cron,
		&i.Timezone,
		&i.NextRunAt,
		&i.WebhookTokenHash,
		&i.Enabled,
		&i.RunCounter,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.GraduatedVersion,
		&i.AllowedDomains,
		&i.AllowPrivateNetwork,
	)
	return i, err
}

const getJobUnscoped = `-- name: GetJobUnscoped :one
SELECT id, workspace_id, name, instruction, spec, spec_overrides, model_id, image, network, run_as_root, limits, self_improve, mode_pin, playbook_version, concurrency, cron, timezone, next_run_at, webhook_token_hash, enabled, run_counter, created_by, created_at, updated_at, archived_at, graduated_version, allowed_domains, allow_private_network FROM jobs WHERE id = $1
`

// unscoped: used by the job actor and webhooks, which are keyed by the globally unique job ID and then act within the job's workspace
func (q *Queries) GetJobUnscoped(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobUnscoped, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Instruction,
		&i.Spec,
		&i.SpecOverrides,
		&i.ModelID,
		&i.Image,
		&i.Network,
		&i.RunAsRoot,
		&i.Limits,
		&i.SelfImprove,
		&i.ModePin,
		&i.PlaybookVersion,
		&i.Concurrency,
		&i.Cron,
		&i.Timezone,
		&i.NextRunAt,
		&i.WebhookTokenHash,
		&i.Enabled,
		&i.RunCounter,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.GraduatedVersion,
		&i.AllowedDomains,
		&i.AllowPrivateNetwork,
	)
	return i, err
}

const getLastRun = `-- name: GetLastRun :one
SELECT id, number, status, queued_at FROM runs
WHERE workspace_id = $1 AND job_id = $2
ORDER BY queued_at DESC, id DESC LIMIT 1
`

type GetLastRunParams struct {
	WorkspaceID string
	JobID       string
}

type GetLastRunRow struct {
	ID       string
	Number   int64
	Status   string
	QueuedAt int64
}

func (q *Queries) GetLastRun(ctx context.Context, arg GetLastRunParams) (GetLastRunRow, error) {
	row := q.db.QueryRowContext(ctx, getLastRun, arg.WorkspaceID, arg.JobID)
	var i GetLastRunRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Status,
		&i.QueuedAt,
	)
	return i, err
}

const getState = `-- name: GetState :one
SELECT value FROM job_state WHERE job_id = $1 AND key = $2
`

type GetStateParams struct {
	JobID string
	Key   string
}

func (q *Queries) GetState(ctx context.Context, arg GetStateParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getState, arg.JobID, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getStateEntry = `-- name: GetStateEntry :one
SELECT value, updated_at FROM job_state WHERE job_id = $1 AND key = $2
`

type GetStateEntryParams struct {
	JobID string
	Key   string
}

type GetStateEntryRow struct {
	Value     string
	UpdatedAt int64
}

func (q *Queries) GetStateEntry(ctx context.Context, arg GetStateEntryParams) (GetStateEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getStateEntry, arg.JobID, arg.Key)
	var i GetStateEntryRow
	err := row.Scan(&i.Value, &i.UpdatedAt)
	return i, err
}

const listActiveRunsForJob = `-- name: ListActiveRunsForJob :many
SELECT id, status FROM runs WHERE workspace_id = $1 AND job_id = $2 AND status IN ('queued', 'provisioning', 'running', 'verifying')
`

type ListActiveRunsForJobParams struct {
	WorkspaceID string
	JobID       string
}

type ListActiveRunsForJobRow struct {
	ID     string
	Status string
}

func (q *Queries) ListActiveRunsForJob(ctx context.Context, arg ListActiveRunsForJobParams) ([]ListActiveRunsForJobRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRunsForJob, arg.WorkspaceID, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveRunsForJobRow{}
	for rows.Next() {
		var i ListActiveRunsForJobRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listState = `-- name: ListState :many
SELECT key, value, updated_at FROM job_state WHERE job_id = $1 ORDER BY key
`

type ListStateRow struct {
	Key       string
	Value     string
	UpdatedAt int64
}

func (q *Queries) ListState(ctx context.Context, jobID string) ([]ListStateRow, error) {
	rows, err := q.db.QueryContext(ctx, listState, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStateRow{}
	for rows.Next() {
		var i ListStateRow
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRunNumber = `-- name: NextRunNumber :one
UPDATE jobs SET run_counter = run_counter + 1 WHERE workspace_id = $1 AND id = $2 RETURNING run_counter
`

type NextRunNumberParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) NextRunNumber(ctx context.Context, arg NextRunNumberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextRunNumber, arg.WorkspaceID, arg.ID)
	var run_counter int64
	err := row.Scan(&run_counter)
	return run_counter, err
}

const recentScriptedRuns = `-- name: RecentScriptedRuns :many
SELECT fell_back FROM runs
WHERE workspace_id = $1 AND job_id = $2 AND mode = 'scripted'
  AND playbook_version >= $3 AND status IN ('succeeded', 'failed', 'timed_out')
ORDER BY number DESC LIMIT 2
`

type RecentScriptedRunsParams struct {
	WorkspaceID  string
	JobID        string
	SinceVersion int64
}

// Two fallbacks in a row since the job graduated demote it to Assisted until it graduates again
func (q *Queries) RecentScriptedRuns(ctx context.Context, arg RecentScriptedRunsParams) ([]bool, error) {
	rows, err := q.db.QueryContext(ctx, recentScriptedRuns, arg.WorkspaceID, arg.JobID, arg.SinceVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []bool{}
	for rows.Next() {
		var fell_back bool
		if err := rows.Scan(&fell_back); err != nil {
			return nil, err
		}
		items = append(items, fell_back)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNextRunAt = `-- name: SetNextRunAt :exec
UPDATE jobs SET next_run_at = $1 WHERE workspace_id = $2 AND id = $3
`

type SetNextRunAtParams struct {
	NextRunAt   *int64
	WorkspaceID string
	ID          string
}

func (q *Queries) SetNextRunAt(ctx context.Context, arg SetNextRunAtParams) error {
	_, err := q.db.ExecContext(ctx, setNextRunAt, arg.NextRunAt, arg.WorkspaceID, arg.ID)
	return err
}

const setPlaybookVersion = `-- name: SetPlaybookVersion :exec
UPDATE jobs SET playbook_version = $1, updated_at = $2 WHERE workspace_id = $3 AND id = $4
`

type SetPlaybookVersionParams struct {
	PlaybookVersion int64
	UpdatedAt       int64
	WorkspaceID     string
	ID              string
}

func (q *Queries) SetPlaybookVersion(ctx context.Context, arg SetPlaybookVersionParams) error {
	_, err := q.db.ExecContext(ctx, setPlaybookVersion,
		arg.PlaybookVersion,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const setState = `-- name: SetState :exec
INSERT INTO job_state (job_id, key, value, updated_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (job_id, key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type SetStateParams struct {
	JobID     string
	Key       string
	Value     string
	UpdatedAt int64
}

func (q *Queries) SetState(ctx context.Context, arg SetStateParams) error {
	_, err := q.db.ExecContext(ctx, setState,
		arg.JobID,
		arg.Key,
		arg.Value,
		arg.UpdatedAt,
	)
	return err
}

const setWebhookTokenHash = `-- name: SetWebhookTokenHash :exec
UPDATE jobs SET webhook_token_hash = $1, updated_at = $2 WHERE workspace_id = $3 AND id = $4
`

type SetWebhookTokenHashParams struct {
	WebhookTokenHash *string
	UpdatedAt        int64
	WorkspaceID      string
	ID               string
}

func (q *Queries) SetWebhookTokenHash(ctx context.Context, arg SetWebhookTokenHashParams) error {
	_, err := q.db.ExecContext(ctx, setWebhookTokenHash,
		arg.WebhookTokenHash,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const updateJob = `-- name: UpdateJob :execrows
UPDATE jobs SET name = $1, instruction = $2, spec = $3, spec_overrides = $4,
  model_id = $5, image = $6, network = $7,
  allowed_domains = $8, allow_private_network = $9, run_as_root = $10,
  limits = $11, self_improve = $12, mode_pin = $13, concurrency = $14,
  cron = $15, timezone = $16, enabled = $17, updated_at = $18
WHERE workspace_id = $19 AND id = $20 AND archived_at IS NULL
`

type UpdateJobParams struct {
	Name                string
	Instruction         string
	Spec                string
	SpecOverrides       string
	ModelID             *string
	Image               *string
	Network             string
	AllowedDomains      string
	AllowPrivateNetwork bool
	RunAsRoot           bool
	Limits              string
	SelfImprove         bool
	ModePin             *string
	Concurrency         string
	Cron                *string
	Timezone            *string
	Enabled             bool
	UpdatedAt           int64
	WorkspaceID         string
	ID                  string
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateJob,
		arg.Name,
		arg.Instruction,
		arg.Spec,
		arg.SpecOverrides,
		arg.ModelID,
		arg.Image,
		arg.Network,
		arg.AllowedDomains,
		arg.AllowPrivateNetwork,
		arg.RunAsRoot,
		arg.Limits,
		arg.SelfImprove,
		arg.ModePin,
		arg.Concurrency,
		arg.Cron,
		arg.Timezone,
		arg.Enabled,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
