// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package mcpserversdb

import (
	"context"
)

const addJobServer = `-- name: AddJobServer :exec
INSERT INTO job_mcp_servers (job_id, mcp_server_id, allowed_tools) VALUES ($1, $2, $3)
`

type AddJobServerParams struct {
	JobID        string
	McpServerID  string
	AllowedTools *string
}

func (q *Queries) AddJobServer(ctx context.Context, arg AddJobServerParams) error {
	_, err := q.db.ExecContext(ctx, addJobServer, arg.JobID, arg.McpServerID, arg.AllowedTools)
	return err
}

const clearExpiredOAuthLogin = `-- name: ClearExpiredOAuthLogin :exec
UPDATE mcp_servers SET oauth_credentials = NULL, oauth_key_id = NULL, oauth_expires_at = NULL, oauth_refreshable = FALSE, oauth_logged_in_at = NULL
WHERE workspace_id = $1 AND id = $2 AND oauth_logged_in_at = $3
`

type ClearExpiredOAuthLoginParams struct {
	WorkspaceID     string
	ID              string
	OauthLoggedInAt *int64
}

// The login is only cleared when it is still the one whose refresh token the authorization server rejected
func (q *Queries) ClearExpiredOAuthLogin(ctx context.Context, arg ClearExpiredOAuthLoginParams) error {
	_, err := q.db.ExecContext(ctx, clearExpiredOAuthLogin, arg.WorkspaceID, arg.ID, arg.OauthLoggedInAt)
	return err
}

const clearJobServers = `-- name: ClearJobServers :exec
DELETE FROM job_mcp_servers WHERE job_id = $1
`

func (q *Queries) ClearJobServers(ctx context.Context, jobID string) error {
	_, err := q.db.ExecContext(ctx, clearJobServers, jobID)
	return err
}

const clearOAuthLogin = `-- name: ClearOAuthLogin :execrows
UPDATE mcp_servers SET oauth_credentials = NULL, oauth_key_id = NULL, oauth_expires_at = NULL, oauth_refreshable = FALSE, oauth_logged_in_at = NULL
WHERE workspace_id = $1 AND id = $2
`

type ClearOAuthLoginParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) ClearOAuthLogin(ctx context.Context, arg ClearOAuthLoginParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearOAuthLogin, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearOAuthPending = `-- name: ClearOAuthPending :execrows
UPDATE mcp_servers SET oauth_pending = NULL WHERE workspace_id = $1 AND id = $2 AND oauth_pending = $3
`

type ClearOAuthPendingParams struct {
	WorkspaceID  string
	ID           string
	OauthPending []byte
}

// Clearing only the login that was read makes it single-use, so a callback URL can't be replayed even by two requests at once
func (q *Queries) ClearOAuthPending(ctx context.Context, arg ClearOAuthPendingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearOAuthPending, arg.WorkspaceID, arg.ID, arg.OauthPending)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createServer = `-- name: CreateServer :exec
INSERT INTO mcp_servers (id, workspace_id, name, description, transport, command, args, env, url, headers, oauth_config, enabled, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
  $11, $12, $13, $13)
`

type CreateServerParams struct {
	ID          string
	WorkspaceID string
	Name        string
	Description *string
	Transport   string
	Command     *string
	Args        string
	Env         string
	Url         *string
	Headers     string
	OauthConfig string
	Enabled     bool
	Now         int64
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) error {
	_, err := q.db.ExecContext(ctx, createServer,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Transport,
		arg.Command,
		arg.Args,
		arg.Env,
		arg.Url,
		arg.Headers,
		arg.OauthConfig,
		arg.Enabled,
		arg.Now,
	)
	return err
}

const deleteServer = `-- name: DeleteServer :execrows
DELETE FROM mcp_servers WHERE workspace_id = $1 AND id = $2
`

type DeleteServerParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) DeleteServer(ctx context.Context, arg DeleteServerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteServer, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOAuthLogin = `-- name: GetOAuthLogin :one
SELECT oauth_credentials, oauth_logged_in_at FROM mcp_servers WHERE workspace_id = $1 AND id = $2
`

type GetOAuthLoginParams struct {
	WorkspaceID string
	ID          string
}

type GetOAuthLoginRow struct {
	OauthCredentials []byte
	OauthLoggedInAt  *int64
}

func (q *Queries) GetOAuthLogin(ctx context.Context, arg GetOAuthLoginParams) (GetOAuthLoginRow, error) {
	row := q.db.QueryRowContext(ctx, getOAuthLogin, arg.WorkspaceID, arg.ID)
	var i GetOAuthLoginRow
	err := row.Scan(&i.OauthCredentials, &i.OauthLoggedInAt)
	return i, err
}

const getOAuthPending = `-- name: GetOAuthPending :one
SELECT oauth_pending FROM mcp_servers WHERE workspace_id = $1 AND id = $2 AND oauth_pending IS NOT NULL
`

type GetOAuthPendingParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) GetOAuthPending(ctx context.Context, arg GetOAuthPendingParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getOAuthPending, arg.WorkspaceID, arg.ID)
	var oauth_pending []byte
	err := row.Scan(&oauth_pending)
	return oauth_pending, err
}

const getServer = `-- name: GetServer :one
SELECT id, workspace_id, name, description, transport, command, args, env, url, headers, tools_cache, tools_cached_at, enabled, oauth_config, oauth_supported, oauth_credentials, oauth_key_id, oauth_expires_at, oauth_refreshable, oauth_logged_in_at, oauth_pending, created_at, updated_at FROM mcp_servers WHERE workspace_id = $1 AND id = $2
`

type GetServerParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) GetServer(ctx context.Context, arg GetServerParams) (McpServer, error) {
	row := q.db.QueryRowContext(ctx, getServer, arg.WorkspaceID, arg.ID)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Transport,
		&i.Command,
		&i.Args,
		&i.Env,
		&i.Url,
		&i.Headers,
		&i.ToolsCache,
		&i.ToolsCachedAt,
		&i.Enabled,
		&i.OauthConfig,
		&i.OauthSupported,
		&i.OauthCredentials,
		&i.OauthKeyID,
		&i.OauthExpiresAt,
		&i.OauthRefreshable,
		&i.OauthLoggedInAt,
		&i.OauthPending,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const leaseOAuthRefresh = `-- name: LeaseOAuthRefresh :execrows
INSERT INTO kv (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = excluded.value WHERE CAST(kv.value AS BIGINT) < CAST($3 AS BIGINT)
`

type LeaseOAuthRefreshParams struct {
	Key   string
	Until string
	Now   int64
}

// An instance-wide key-value row whose key names the server and whose value is when the lease runs out, so one replica at a time spends the login's refresh token
// A lease that ran out is taken over, since its replica died before releasing it
func (q *Queries) LeaseOAuthRefresh(ctx context.Context, arg LeaseOAuthRefreshParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, leaseOAuthRefresh, arg.Key, arg.Until, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listJobServers = `-- name: ListJobServers :many
SELECT s.id, s.workspace_id, s.name, s.transport, s.command, s.args, s.env, s.url, s.headers, s.enabled, s.oauth_credentials, s.oauth_logged_in_at, jm.allowed_tools
FROM job_mcp_servers jm JOIN mcp_servers s ON s.id = jm.mcp_server_id
WHERE s.workspace_id = $1 AND jm.job_id = $2 ORDER BY s.name
`

type ListJobServersParams struct {
	WorkspaceID string
	JobID       string
}

type ListJobServersRow struct {
	ID               string
	WorkspaceID      string
	Name             string
	Transport        string
	Command          *string
	Args             string
	Env              string
	Url              *string
	Headers          string
	Enabled          bool
	OauthCredentials []byte
	OauthLoggedInAt  *int64
	AllowedTools     *string
}

func (q *Queries) ListJobServers(ctx context.Context, arg ListJobServersParams) ([]ListJobServersRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobServers, arg.WorkspaceID, arg.JobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobServersRow{}
	for rows.Next() {
		var i ListJobServersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Transport,
			&i.Command,
			&i.Args,
			&i.Env,
			&i.Url,
			&i.Headers,
			&i.Enabled,
			&i.OauthCredentials,
			&i.OauthLoggedInAt,
			&i.AllowedTools,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServerNames = `-- name: ListServerNames :many
SELECT name FROM mcp_servers WHERE workspace_id = $1 AND enabled = TRUE ORDER BY name
`

func (q *Queries) ListServerNames(ctx context.Context, workspaceID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listServerNames, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseOAuthRefresh = `-- name: ReleaseOAuthRefresh :exec
DELETE FROM kv WHERE key = $1 AND value = $2
`

type ReleaseOAuthRefreshParams struct {
	Key   string
	Until string
}

// Only the lease that was taken is released, so a replica whose lease ran out can't release the one that took over
func (q *Queries) ReleaseOAuthRefresh(ctx context.Context, arg ReleaseOAuthRefreshParams) error {
	_, err := q.db.ExecContext(ctx, releaseOAuthRefresh, arg.Key, arg.Until)
	return err
}

const saveOAuthLogin = `-- name: SaveOAuthLogin :exec
UPDATE mcp_servers SET oauth_credentials = $1, oauth_key_id = $2, oauth_expires_at = $3,
  oauth_refreshable = $4, oauth_logged_in_at = $5, oauth_supported = TRUE
WHERE workspace_id = $6 AND id = $7
`

type SaveOAuthLoginParams struct {
	OauthCredentials []byte
	OauthKeyID       *string
	OauthExpiresAt   *int64
	OauthRefreshable bool
	OauthLoggedInAt  *int64
	WorkspaceID      string
	ID               string
}

func (q *Queries) SaveOAuthLogin(ctx context.Context, arg SaveOAuthLoginParams) error {
	_, err := q.db.ExecContext(ctx, saveOAuthLogin,
		arg.OauthCredentials,
		arg.OauthKeyID,
		arg.OauthExpiresAt,
		arg.OauthRefreshable,
		arg.OauthLoggedInAt,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const saveOAuthTokens = `-- name: SaveOAuthTokens :exec
UPDATE mcp_servers SET oauth_credentials = $1, oauth_key_id = $2, oauth_expires_at = $3,
  oauth_refreshable = $4
WHERE workspace_id = $5 AND id = $6 AND oauth_logged_in_at = $7
`

type SaveOAuthTokensParams struct {
	OauthCredentials []byte
	OauthKeyID       *string
	OauthExpiresAt   *int64
	OauthRefreshable bool
	WorkspaceID      string
	ID               string
	OauthLoggedInAt  *int64
}

// A refresh only lands on the login it refreshed, so it can't bring back a login that was logged out or replaced meanwhile
func (q *Queries) SaveOAuthTokens(ctx context.Context, arg SaveOAuthTokensParams) error {
	_, err := q.db.ExecContext(ctx, saveOAuthTokens,
		arg.OauthCredentials,
		arg.OauthKeyID,
		arg.OauthExpiresAt,
		arg.OauthRefreshable,
		arg.WorkspaceID,
		arg.ID,
		arg.OauthLoggedInAt,
	)
	return err
}

const setOAuthPending = `-- name: SetOAuthPending :exec
UPDATE mcp_servers SET oauth_pending = $1 WHERE workspace_id = $2 AND id = $3
`

type SetOAuthPendingParams struct {
	OauthPending []byte
	WorkspaceID  string
	ID           string
}

func (q *Queries) SetOAuthPending(ctx context.Context, arg SetOAuthPendingParams) error {
	_, err := q.db.ExecContext(ctx, setOAuthPending, arg.OauthPending, arg.WorkspaceID, arg.ID)
	return err
}

const setOAuthSupported = `-- name: SetOAuthSupported :exec
UPDATE mcp_servers SET oauth_supported = $1 WHERE workspace_id = $2 AND id = $3
`

type SetOAuthSupportedParams struct {
	OauthSupported *bool
	WorkspaceID    string
	ID             string
}

func (q *Queries) SetOAuthSupported(ctx context.Context, arg SetOAuthSupportedParams) error {
	_, err := q.db.ExecContext(ctx, setOAuthSupported, arg.OauthSupported, arg.WorkspaceID, arg.ID)
	return err
}

const setToolsCache = `-- name: SetToolsCache :exec
UPDATE mcp_servers SET tools_cache = $1, tools_cached_at = $2 WHERE workspace_id = $3 AND id = $4
`

type SetToolsCacheParams struct {
	ToolsCache    *string
	ToolsCachedAt *int64
	WorkspaceID   string
	ID            string
}

func (q *Queries) SetToolsCache(ctx context.Context, arg SetToolsCacheParams) error {
	_, err := q.db.ExecContext(ctx, setToolsCache,
		arg.ToolsCache,
		arg.ToolsCachedAt,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const updateServer = `-- name: UpdateServer :execrows
UPDATE mcp_servers SET name = $1, description = $2, transport = $3, command = $4,
  args = $5, env = $6, url = $7, headers = $8, oauth_config = $9,
  enabled = $10, updated_at = $11
WHERE workspace_id = $12 AND id = $13
`

type UpdateServerParams struct {
	Name        string
	Description *string
	Transport   string
	Command     *string
	Args        string
	Env         string
	Url         *string
	Headers     string
	OauthConfig string
	Enabled     bool
	UpdatedAt   int64
	WorkspaceID string
	ID          string
}

func (q *Queries) UpdateServer(ctx context.Context, arg UpdateServerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateServer,
		arg.Name,
		arg.Description,
		arg.Transport,
		arg.Command,
		arg.Args,
		arg.Env,
		arg.Url,
		arg.Headers,
		arg.OauthConfig,
		arg.Enabled,
		arg.UpdatedAt,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
