// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package runsdb

import (
	"context"
)

const cancelQueuedRun = `-- name: CancelQueuedRun :execrows
UPDATE runs SET status = 'cancelled', finished_at = $1, error = 'Cancelled before it started'
WHERE workspace_id = $2 AND id = $3 AND status = 'queued'
`

type CancelQueuedRunParams struct {
	FinishedAt  *int64
	WorkspaceID string
	ID          string
}

func (q *Queries) CancelQueuedRun(ctx context.Context, arg CancelQueuedRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelQueuedRun, arg.FinishedAt, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimRun = `-- name: ClaimRun :execrows
UPDATE runs SET status = 'provisioning', host_id = $1, started_at = $2, heartbeat_at = $2, ms_queue = $2 - queued_at
WHERE id = $3 AND status = 'queued'
`

type ClaimRunParams struct {
	HostID    *string
	StartedAt *int64
	ID        string
}

// unscoped: the run ID comes from the taskpool, and only a queued run can be claimed
func (q *Queries) ClaimRun(ctx context.Context, arg ClaimRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimRun, arg.HostID, arg.StartedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countActiveRuns = `-- name: CountActiveRuns :one
SELECT COUNT(*) FROM runs WHERE workspace_id = $1 AND status IN ('queued', 'provisioning', 'running', 'verifying')
`

func (q *Queries) CountActiveRuns(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveRuns, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :exec
INSERT INTO runs (id, workspace_id, job_id, number, status, mode, trigger, triggered_by, input, instructions, playbook_version, model_id, queued_at, error, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type CreateRunParams struct {
	ID              string
	WorkspaceID     string
	JobID           string
	Number          int64
	Status          string
	Mode            string
	Trigger         string
	TriggeredBy     *string
	Input           *string
	Instructions    *string
	PlaybookVersion int64
	ModelID         *string
	QueuedAt        int64
	Error           *string
	FinishedAt      *int64
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun,
		arg.ID,
		arg.WorkspaceID,
		arg.JobID,
		arg.Number,
		arg.Status,
		arg.Mode,
		arg.Trigger,
		arg.TriggeredBy,
		arg.Input,
		arg.Instructions,
		arg.PlaybookVersion,
		arg.ModelID,
		arg.QueuedAt,
		arg.Error,
		arg.FinishedAt,
	)
	return err
}

const deleteFinishedRun = `-- name: DeleteFinishedRun :execrows
DELETE FROM runs WHERE workspace_id = $1 AND id = $2
  AND status IN ('succeeded', 'failed', 'cancelled', 'timed_out', 'skipped') AND reflection <> 'pending'
`

type DeleteFinishedRunParams struct {
	WorkspaceID string
	ID          string
}

// The status guard keeps a run that was claimed or started reflecting since it was loaded from being deleted underneath its runner
func (q *Queries) DeleteFinishedRun(ctx context.Context, arg DeleteFinishedRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFinishedRun, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePruneWatermark = `-- name: DeletePruneWatermark :exec
DELETE FROM kv WHERE key = $1
`

// unscoped: an instance-wide key-value row whose key names the workspace
func (q *Queries) DeletePruneWatermark(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deletePruneWatermark, key)
	return err
}

const deleteRunEventsOf = `-- name: DeleteRunEventsOf :exec
DELETE FROM run_events WHERE run_id IN (SELECT id FROM runs WHERE workspace_id = $1 AND id = $2)
`

type DeleteRunEventsOfParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) DeleteRunEventsOf(ctx context.Context, arg DeleteRunEventsOfParams) error {
	_, err := q.db.ExecContext(ctx, deleteRunEventsOf, arg.WorkspaceID, arg.ID)
	return err
}

const finishRun = `-- name: FinishRun :execrows
UPDATE runs SET status = $1, finished_at = $2, ms_total = $3,
  ms_llm = $4, ms_tools = $5, turns = $6,
  tok_in = $7, tok_out = $8, tok_cache_read = $9, tok_cache_write = $10,
  cost = $11, summary = $12, outputs = $13, error = $14, broker_token_hash = NULL,
  reflection = $15, reflection_requested_at = $16,
  fell_back = $17, verify_cost = $18, verify_tokens = $19
WHERE id = $20 AND status IN ('queued', 'provisioning', 'running', 'verifying')
`

type FinishRunParams struct {
	Status                string
	FinishedAt            *int64
	MsTotal               *int64
	MsLlm                 int64
	MsTools               int64
	Turns                 int64
	TokIn                 int64
	TokOut                int64
	TokCacheRead          int64
	TokCacheWrite         int64
	Cost                  int64
	Summary               *string
	Outputs               *string
	Error                 *string
	Reflection            string
	ReflectionRequestedAt *int64
	FellBack              bool
	VerifyCost            int64
	VerifyTokens          int64
	ID                    string
}

// unscoped: only the replica executing the run, or the reconciler, finishes it
func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishRun,
		arg.Status,
		arg.FinishedAt,
		arg.MsTotal,
		arg.MsLlm,
		arg.MsTools,
		arg.Turns,
		arg.TokIn,
		arg.TokOut,
		arg.TokCacheRead,
		arg.TokCacheWrite,
		arg.Cost,
		arg.Summary,
		arg.Outputs,
		arg.Error,
		arg.Reflection,
		arg.ReflectionRequestedAt,
		arg.FellBack,
		arg.VerifyCost,
		arg.VerifyTokens,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPruneWatermark = `-- name: GetPruneWatermark :one
SELECT value FROM kv WHERE key = $1
`

// unscoped: an instance-wide key-value row whose key names the workspace
func (q *Queries) GetPruneWatermark(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPruneWatermark, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getRun = `-- name: GetRun :one
SELECT id, workspace_id, job_id, number, status, mode, fell_back, trigger, triggered_by, input, instructions, playbook_version, model_id, image_id, image_ref, host_id, heartbeat_at, broker_token_hash, sandbox_adapter, sandbox_id, sandbox_isolation, queued_at, started_at, finished_at, ms_queue, ms_provision, ms_llm, ms_tools, ms_total, turns, tok_in, tok_out, tok_cache_read, tok_cache_write, cost, summary, outputs, error, cancel_requested, reflection, reflection_requested_at, reflection_error, reflection_summary, reflection_ops, reflection_version, reflection_cost, reflection_tokens, verify_cost, verify_tokens FROM runs WHERE workspace_id = $1 AND id = $2
`

type GetRunParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, arg.WorkspaceID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.JobID,
		&i.Number,
		&i.Status,
		&i.Mode,
		&i.FellBack,
		&i.Trigger,
		&i.TriggeredBy,
		&i.Input,
		&i.Instructions,
		&i.PlaybookVersion,
		&i.ModelID,
		&i.ImageID,
		&i.ImageRef,
		&i.HostID,
		&i.HeartbeatAt,
		&i.BrokerTokenHash,
		&i.SandboxAdapter,
		&i.SandboxID,
		&i.SandboxIsolation,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.MsQueue,
		&i.MsProvision,
		&i.MsLlm,
		&i.MsTools,
		&i.MsTotal,
		&i.Turns,
		&i.TokIn,
		&i.TokOut,
		&i.TokCacheRead,
		&i.TokCacheWrite,
		&i.Cost,
		&i.Summary,
		&i.Outputs,
		&i.Error,
		&i.CancelRequested,
		&i.Reflection,
		&i.ReflectionRequestedAt,
		&i.ReflectionError,
		&i.ReflectionSummary,
		&i.ReflectionOps,
		&i.ReflectionVersion,
		&i.ReflectionCost,
		&i.ReflectionTokens,
		&i.VerifyCost,
		&i.VerifyTokens,
	)
	return i, err
}

const getRunByBrokerToken = `-- name: GetRunByBrokerToken :one
SELECT id FROM runs WHERE broker_token_hash = $1 AND status IN ('provisioning', 'running', 'verifying')
`

// unscoped: the broker token identifies the run and through it the workspace
func (q *Queries) GetRunByBrokerToken(ctx context.Context, brokerTokenHash *string) (string, error) {
	row := q.db.QueryRowContext(ctx, getRunByBrokerToken, brokerTokenHash)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getRunUnscoped = `-- name: GetRunUnscoped :one
SELECT id, workspace_id, job_id, number, status, mode, fell_back, trigger, triggered_by, input, instructions, playbook_version, model_id, image_id, image_ref, host_id, heartbeat_at, broker_token_hash, sandbox_adapter, sandbox_id, sandbox_isolation, queued_at, started_at, finished_at, ms_queue, ms_provision, ms_llm, ms_tools, ms_total, turns, tok_in, tok_out, tok_cache_read, tok_cache_write, cost, summary, outputs, error, cancel_requested, reflection, reflection_requested_at, reflection_error, reflection_summary, reflection_ops, reflection_version, reflection_cost, reflection_tokens, verify_cost, verify_tokens FROM runs WHERE id = $1
`

// unscoped: used by the runs taskpool, which is keyed by the globally unique run ID
func (q *Queries) GetRunUnscoped(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRunUnscoped, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.JobID,
		&i.Number,
		&i.Status,
		&i.Mode,
		&i.FellBack,
		&i.Trigger,
		&i.TriggeredBy,
		&i.Input,
		&i.Instructions,
		&i.PlaybookVersion,
		&i.ModelID,
		&i.ImageID,
		&i.ImageRef,
		&i.HostID,
		&i.HeartbeatAt,
		&i.BrokerTokenHash,
		&i.SandboxAdapter,
		&i.SandboxID,
		&i.SandboxIsolation,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.MsQueue,
		&i.MsProvision,
		&i.MsLlm,
		&i.MsTools,
		&i.MsTotal,
		&i.Turns,
		&i.TokIn,
		&i.TokOut,
		&i.TokCacheRead,
		&i.TokCacheWrite,
		&i.Cost,
		&i.Summary,
		&i.Outputs,
		&i.Error,
		&i.CancelRequested,
		&i.Reflection,
		&i.ReflectionRequestedAt,
		&i.ReflectionError,
		&i.ReflectionSummary,
		&i.ReflectionOps,
		&i.ReflectionVersion,
		&i.ReflectionCost,
		&i.ReflectionTokens,
		&i.VerifyCost,
		&i.VerifyTokens,
	)
	return i, err
}

const heartbeatRun = `-- name: HeartbeatRun :one
UPDATE runs SET heartbeat_at = $1 WHERE id = $2 RETURNING cancel_requested
`

type HeartbeatRunParams struct {
	HeartbeatAt *int64
	ID          string
}

// unscoped: only the replica executing the run sends heartbeats
func (q *Queries) HeartbeatRun(ctx context.Context, arg HeartbeatRunParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, heartbeatRun, arg.HeartbeatAt, arg.ID)
	var cancel_requested bool
	err := row.Scan(&cancel_requested)
	return cancel_requested, err
}

const listFinishedRunIDsBefore = `-- name: ListFinishedRunIDsBefore :many
SELECT id FROM runs WHERE workspace_id = $1 AND finished_at < $2 AND finished_at >= $3
`

type ListFinishedRunIDsBeforeParams struct {
	WorkspaceID string
	Before      *int64
	After       *int64
}

func (q *Queries) ListFinishedRunIDsBefore(ctx context.Context, arg ListFinishedRunIDsBeforeParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listFinishedRunIDsBefore, arg.WorkspaceID, arg.Before, arg.After)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunEvents = `-- name: ListRunEvents :many
SELECT seq, ts, type, span_id, ms, payload FROM run_events
WHERE run_id = $1 AND seq > $2 ORDER BY seq LIMIT $3
`

type ListRunEventsParams struct {
	RunID    string
	AfterSeq int64
	MaxRows  int32
}

type ListRunEventsRow struct {
	Seq     int64
	Ts      int64
	Type    string
	SpanID  *string
	Ms      *int64
	Payload string
}

func (q *Queries) ListRunEvents(ctx context.Context, arg ListRunEventsParams) ([]ListRunEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunEvents, arg.RunID, arg.AfterSeq, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunEventsRow{}
	for rows.Next() {
		var i ListRunEventsRow
		if err := rows.Scan(
			&i.Seq,
			&i.Ts,
			&i.Type,
			&i.SpanID,
			&i.Ms,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunIDs = `-- name: ListRunIDs :many
SELECT id FROM runs WHERE workspace_id = $1
`

func (q *Queries) ListRunIDs(ctx context.Context, workspaceID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRunIDs, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleRuns = `-- name: ListStaleRuns :many
SELECT id, sandbox_id FROM runs
WHERE status IN ('provisioning', 'running', 'verifying') AND heartbeat_at < $1
`

type ListStaleRunsRow struct {
	ID        string
	SandboxID *string
}

// unscoped: the reconciler looks across workspaces for runs whose replica stopped sending heartbeats
func (q *Queries) ListStaleRuns(ctx context.Context, cutoff *int64) ([]ListStaleRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStaleRuns, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleRunsRow{}
	for rows.Next() {
		var i ListStaleRunsRow
		if err := rows.Scan(&i.ID, &i.SandboxID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceIDs = `-- name: ListWorkspaceIDs :many
SELECT id FROM workspaces
`

// unscoped: retention visits every workspace with its own retention setting
func (q *Queries) ListWorkspaceIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestCancel = `-- name: RequestCancel :execrows
UPDATE runs SET cancel_requested = TRUE WHERE workspace_id = $1 AND id = $2 AND status IN ('queued', 'provisioning', 'running', 'verifying')
`

type RequestCancelParams struct {
	WorkspaceID string
	ID          string
}

func (q *Queries) RequestCancel(ctx context.Context, arg RequestCancelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requestCancel, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setPruneWatermark = `-- name: SetPruneWatermark :exec
INSERT INTO kv (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type SetPruneWatermarkParams struct {
	Key   string
	Value string
}

// unscoped: an instance-wide key-value row whose key names the workspace
func (q *Queries) SetPruneWatermark(ctx context.Context, arg SetPruneWatermarkParams) error {
	_, err := q.db.ExecContext(ctx, setPruneWatermark, arg.Key, arg.Value)
	return err
}

const setRunBrokerToken = `-- name: SetRunBrokerToken :exec
UPDATE runs SET broker_token_hash = $1 WHERE id = $2
`

type SetRunBrokerTokenParams struct {
	BrokerTokenHash *string
	ID              string
}

// unscoped: only the replica executing the run sets its broker token
func (q *Queries) SetRunBrokerToken(ctx context.Context, arg SetRunBrokerTokenParams) error {
	_, err := q.db.ExecContext(ctx, setRunBrokerToken, arg.BrokerTokenHash, arg.ID)
	return err
}

const setRunFellBack = `-- name: SetRunFellBack :exec
UPDATE runs SET fell_back = TRUE WHERE id = $1
`

// unscoped: only the replica executing the run records that its script fell back to the agent
func (q *Queries) SetRunFellBack(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setRunFellBack, id)
	return err
}

const setRunSandbox = `-- name: SetRunSandbox :exec
UPDATE runs SET sandbox_adapter = $1, sandbox_id = $2, sandbox_isolation = $3,
  image_ref = $4, image_id = $5, model_id = $6, ms_provision = $7
WHERE id = $8
`

type SetRunSandboxParams struct {
	SandboxAdapter   *string
	SandboxID        *string
	SandboxIsolation *string
	ImageRef         *string
	ImageID          *string
	ModelID          *string
	MsProvision      *int64
	ID               string
}

// unscoped: only the replica executing the run records its sandbox
func (q *Queries) SetRunSandbox(ctx context.Context, arg SetRunSandboxParams) error {
	_, err := q.db.ExecContext(ctx, setRunSandbox,
		arg.SandboxAdapter,
		arg.SandboxID,
		arg.SandboxIsolation,
		arg.ImageRef,
		arg.ImageID,
		arg.ModelID,
		arg.MsProvision,
		arg.ID,
	)
	return err
}

const setRunStatus = `-- name: SetRunStatus :execrows
UPDATE runs SET status = $1 WHERE id = $2 AND status IN ('provisioning', 'running', 'verifying')
`

type SetRunStatusParams struct {
	Status string
	ID     string
}

// unscoped: only the replica executing the run changes its live status
func (q *Queries) SetRunStatus(ctx context.Context, arg SetRunStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setRunStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sumCostSince = `-- name: SumCostSince :one
SELECT CAST(COALESCE(SUM(cost + reflection_cost + verify_cost), 0) AS BIGINT) FROM runs WHERE workspace_id = $1 AND queued_at >= $2
`

type SumCostSinceParams struct {
	WorkspaceID string
	Since       int64
}

func (q *Queries) SumCostSince(ctx context.Context, arg SumCostSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumCostSince, arg.WorkspaceID, arg.Since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
