// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package imagesdb

import (
	"context"
)

const createImage = `-- name: CreateImage :exec
INSERT INTO images (id, job_id, dockerfile_hash, dockerfile, status, created_at)
VALUES ($1, $2, $3, $4, 'queued', $5)
`

type CreateImageParams struct {
	ID             string
	JobID          string
	DockerfileHash string
	Dockerfile     string
	CreatedAt      int64
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.ExecContext(ctx, createImage,
		arg.ID,
		arg.JobID,
		arg.DockerfileHash,
		arg.Dockerfile,
		arg.CreatedAt,
	)
	return err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteImage, id)
	return err
}

const getImage = `-- name: GetImage :one
SELECT id, job_id, dockerfile_hash, dockerfile, base_digest, status, ref, digest, size_bytes, error, log_key, created_at, started_at, finished_at FROM images WHERE id = $1
`

func (q *Queries) GetImage(ctx context.Context, id string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.DockerfileHash,
		&i.Dockerfile,
		&i.BaseDigest,
		&i.Status,
		&i.Ref,
		&i.Digest,
		&i.SizeBytes,
		&i.Error,
		&i.LogKey,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const latestImageForHash = `-- name: LatestImageForHash :one
SELECT id, job_id, dockerfile_hash, dockerfile, base_digest, status, ref, digest, size_bytes, error, log_key, created_at, started_at, finished_at FROM images WHERE job_id = $1 AND dockerfile_hash = $2 ORDER BY created_at DESC, id DESC LIMIT 1
`

type LatestImageForHashParams struct {
	JobID          string
	DockerfileHash string
}

func (q *Queries) LatestImageForHash(ctx context.Context, arg LatestImageForHashParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, latestImageForHash, arg.JobID, arg.DockerfileHash)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.DockerfileHash,
		&i.Dockerfile,
		&i.BaseDigest,
		&i.Status,
		&i.Ref,
		&i.Digest,
		&i.SizeBytes,
		&i.Error,
		&i.LogKey,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const latestReadyImageForHash = `-- name: LatestReadyImageForHash :one
SELECT id, job_id, dockerfile_hash, dockerfile, base_digest, status, ref, digest, size_bytes, error, log_key, created_at, started_at, finished_at FROM images WHERE job_id = $1 AND dockerfile_hash = $2 AND status = 'ready' ORDER BY created_at DESC, id DESC LIMIT 1
`

type LatestReadyImageForHashParams struct {
	JobID          string
	DockerfileHash string
}

func (q *Queries) LatestReadyImageForHash(ctx context.Context, arg LatestReadyImageForHashParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, latestReadyImageForHash, arg.JobID, arg.DockerfileHash)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.DockerfileHash,
		&i.Dockerfile,
		&i.BaseDigest,
		&i.Status,
		&i.Ref,
		&i.Digest,
		&i.SizeBytes,
		&i.Error,
		&i.LogKey,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listImageIDsOfWorkspace = `-- name: ListImageIDsOfWorkspace :many
SELECT i.id FROM images i JOIN jobs j ON j.id = i.job_id WHERE j.workspace_id = $1
`

func (q *Queries) ListImageIDsOfWorkspace(ctx context.Context, workspaceID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listImageIDsOfWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesForGC = `-- name: ListImagesForGC :many
SELECT i.id, i.job_id, i.dockerfile_hash, i.ref, i.status FROM images i ORDER BY i.job_id, i.created_at DESC
`

type ListImagesForGCRow struct {
	ID             string
	JobID          string
	DockerfileHash string
	Ref            *string
	Status         string
}

func (q *Queries) ListImagesForGC(ctx context.Context) ([]ListImagesForGCRow, error) {
	rows, err := q.db.QueryContext(ctx, listImagesForGC)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImagesForGCRow{}
	for rows.Next() {
		var i ListImagesForGCRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.DockerfileHash,
			&i.Ref,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBuilding = `-- name: MarkBuilding :exec
UPDATE images SET status = 'building', started_at = $1, base_digest = $2, log_key = $3
WHERE id = $4 AND status IN ('queued', 'building')
`

type MarkBuildingParams struct {
	StartedAt  *int64
	BaseDigest *string
	LogKey     *string
	ID         string
}

func (q *Queries) MarkBuilding(ctx context.Context, arg MarkBuildingParams) error {
	_, err := q.db.ExecContext(ctx, markBuilding,
		arg.StartedAt,
		arg.BaseDigest,
		arg.LogKey,
		arg.ID,
	)
	return err
}

const markFailed = `-- name: MarkFailed :exec
UPDATE images SET status = 'failed', error = $1, finished_at = $2 WHERE id = $3
`

type MarkFailedParams struct {
	Error      *string
	FinishedAt *int64
	ID         string
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) error {
	_, err := q.db.ExecContext(ctx, markFailed, arg.Error, arg.FinishedAt, arg.ID)
	return err
}

const markReady = `-- name: MarkReady :exec
UPDATE images SET status = 'ready', ref = $1, digest = $2, size_bytes = $3, finished_at = $4 WHERE id = $5
`

type MarkReadyParams struct {
	Ref        *string
	Digest     *string
	SizeBytes  *int64
	FinishedAt *int64
	ID         string
}

func (q *Queries) MarkReady(ctx context.Context, arg MarkReadyParams) error {
	_, err := q.db.ExecContext(ctx, markReady,
		arg.Ref,
		arg.Digest,
		arg.SizeBytes,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const recentDockerfileHashes = `-- name: RecentDockerfileHashes :many
SELECT DISTINCT v.dockerfile_hash FROM playbook_versions v
WHERE v.job_id = $1 AND v.dockerfile_hash IS NOT NULL
  AND v.version > (SELECT COALESCE(MAX(pv.version), 0) - 5 FROM playbook_versions pv WHERE pv.job_id = $1)
  AND EXISTS (SELECT 1 FROM jobs j WHERE j.id = v.job_id AND j.archived_at IS NULL)
`

// unscoped: GC walks the images of every workspace and reaches the job by its globally unique ID
// A deleted job is only archived and never comes back, so none of its Dockerfiles count as in use and GC collects all of its images
func (q *Queries) RecentDockerfileHashes(ctx context.Context, jobID string) ([]*string, error) {
	rows, err := q.db.QueryContext(ctx, recentDockerfileHashes, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var dockerfile_hash *string
		if err := rows.Scan(&dockerfile_hash); err != nil {
			return nil, err
		}
		items = append(items, dockerfile_hash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
