//go:build unit

package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestSetResolversKeepsSearchAndOptions(t *testing.T) {
	path := filepath.Join(t.TempDir(), "resolv.conf")
	require.NoError(t, os.WriteFile(path, []byte("# Generated by Docker Engine.\nnameserver 127.0.0.11\nsearch corp.example\noptions ndots:0\n"), 0o600))

	require.NoError(t, setResolvers(path, []string{"8.8.8.8", " 8.8.4.4", ""}))

	data, err := os.ReadFile(path) // #nosec G304 -- a file in the test's temp directory
	require.NoError(t, err)
	require.Equal(t, "nameserver 8.8.8.8\nnameserver 8.8.4.4\nsearch corp.example\noptions ndots:0\n", string(data))
}
